2024-01-23 19:07:57,340:WARNING:discord.client: PyNaCl is not installed, voice will NOT be supported
2024-01-23 19:07:57,346:INFO:discord.client: logging in using static token
2024-01-23 19:07:57,346:INFO:discord.client: logging in using static token
2024-01-23 19:07:58,521:INFO:discord.gateway: Shard ID None has connected to Gateway (Session ID: e2390ef741f55a6804661aae141b8051).
2024-01-23 19:07:58,521:INFO:discord.gateway: Shard ID None has connected to Gateway (Session ID: e2390ef741f55a6804661aae141b8051).
2024-01-23 19:08:00,809:WARNING:discord.http: We are being rate limited. PUT https://discord.com/api/v10/applications/1198496806124933190/commands responded with 429. Retrying in 8.91 seconds.
2024-01-23 19:08:00,809:WARNING:discord.http: We are being rate limited. PUT https://discord.com/api/v10/applications/1198496806124933190/commands responded with 429. Retrying in 8.91 seconds.
2024-01-23 19:12:47,324:WARNING:discord.client: PyNaCl is not installed, voice will NOT be supported
2024-01-23 19:12:47,330:INFO:discord.client: logging in using static token
2024-01-23 19:12:47,330:INFO:discord.client: logging in using static token
2024-01-23 19:12:48,636:INFO:discord.gateway: Shard ID None has connected to Gateway (Session ID: 97832c69c0dfc11aaafc61079f02565d).
2024-01-23 19:12:48,636:INFO:discord.gateway: Shard ID None has connected to Gateway (Session ID: 97832c69c0dfc11aaafc61079f02565d).
2024-01-23 19:16:29,534:WARNING:discord.client: PyNaCl is not installed, voice will NOT be supported
2024-01-23 19:16:29,540:INFO:discord.client: logging in using static token
2024-01-23 19:16:30,682:INFO:discord.gateway: Shard ID None has connected to Gateway (Session ID: a16464e63ed9c5433a32a13891a5c88e).
2024-01-23 19:16:36,527:INFO:discord: Command: /vouches shauuu_ div1 by shauuu_
2024-01-23 20:00:30,459:INFO:discord.gateway: Shard ID None has successfully RESUMED session a16464e63ed9c5433a32a13891a5c88e.
2024-01-23 20:16:05,189:WARNING:discord.client: PyNaCl is not installed, voice will NOT be supported
2024-01-23 20:16:16,520:WARNING:discord.client: PyNaCl is not installed, voice will NOT be supported
2024-01-23 20:16:16,540:INFO:discord.client: logging in using static token
2024-01-23 20:16:17,684:INFO:discord.gateway: Shard ID None has connected to Gateway (Session ID: eda485f5499e9f77133ae2f1693687a6).
2024-01-23 20:17:11,404:INFO:discord: Command: /vouches shauuu_ Divisão 1 by shauuu_
2024-01-23 20:33:47,092:WARNING:discord.client: PyNaCl is not installed, voice will NOT be supported
2024-01-23 20:33:47,163:INFO:discord.client: logging in using static token
2024-01-23 20:33:48,385:INFO:discord.gateway: Shard ID None has connected to Gateway (Session ID: 42aab7c3d633242beeda7f13a95657da).
2024-01-23 20:34:14,006:INFO:discord: Command: /promote shauuu_ Divisão 1 by shauuu_
2024-01-23 20:34:54,267:WARNING:discord.client: PyNaCl is not installed, voice will NOT be supported
2024-01-23 20:34:54,278:INFO:discord.client: logging in using static token
2024-01-23 20:34:55,438:INFO:discord.gateway: Shard ID None has connected to Gateway (Session ID: deeff3d2172c10d3072e179963f2bc89).
2024-01-23 20:35:04,515:INFO:discord: Command: /promote shauuu_ Divisão 1 by shauuu_
2024-01-23 20:36:09,861:WARNING:discord.client: PyNaCl is not installed, voice will NOT be supported
2024-01-23 20:36:09,894:INFO:discord.client: logging in using static token
2024-01-23 20:36:11,091:INFO:discord.gateway: Shard ID None has connected to Gateway (Session ID: 61f6cdaf7456745fd101cd00811b717c).
2024-01-23 20:36:23,054:INFO:discord: Command: /promote shauuu_ Divisão 1 by shauuu_
2024-01-23 20:36:52,470:WARNING:discord.client: PyNaCl is not installed, voice will NOT be supported
2024-01-23 20:36:52,485:INFO:discord.client: logging in using static token
2024-01-23 20:36:53,599:INFO:discord.gateway: Shard ID None has connected to Gateway (Session ID: 00668cab95aa581a82939a5532f12041).
2024-01-23 20:37:21,248:INFO:discord: Command: /promote shauuu_ Divisão 1 by shauuu_
2024-01-23 20:37:21,934:ERROR:discord.app_commands.tree: Ignoring exception in command 'promote'
Traceback (most recent call last):
  File "D:\PyCharmProjects\Vouch Bot\.venv\lib\site-packages\discord\app_commands\commands.py", line 827, in _do_call
    return await self._callback(self.binding, interaction, **params)  # type: ignore
  File "D:\PyCharmProjects\Vouch Bot\commands.py", line 144, in promote
    await member.add_roles(role)
  File "D:\PyCharmProjects\Vouch Bot\.venv\lib\site-packages\discord\member.py", line 1051, in add_roles
    await req(guild_id, user_id, role.id, reason=reason)
AttributeError: 'NoneType' object has no attribute 'id'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\PyCharmProjects\Vouch Bot\.venv\lib\site-packages\discord\app_commands\tree.py", line 1248, in _call
    await command._invoke_with_namespace(interaction, namespace)
  File "D:\PyCharmProjects\Vouch Bot\.venv\lib\site-packages\discord\app_commands\commands.py", line 853, in _invoke_with_namespace
    return await self._do_call(interaction, transformed_values)
  File "D:\PyCharmProjects\Vouch Bot\.venv\lib\site-packages\discord\app_commands\commands.py", line 846, in _do_call
    raise CommandInvokeError(self, e) from e
discord.app_commands.errors.CommandInvokeError: Command 'promote' raised an exception: AttributeError: 'NoneType' object has no attribute 'id'
2024-01-23 20:41:59,948:WARNING:discord.client: PyNaCl is not installed, voice will NOT be supported
2024-01-23 20:41:59,968:INFO:discord.client: logging in using static token
2024-01-23 20:42:01,213:INFO:discord.gateway: Shard ID None has connected to Gateway (Session ID: 45e1db9adacdcb5e6dd0b55c7f2993bd).
2024-01-23 20:42:12,348:INFO:discord: Command: /promote shauuu_ Divisão 2 by shauuu_
2024-01-23 20:42:12,838:ERROR:discord.app_commands.tree: Ignoring exception in command 'promote'
Traceback (most recent call last):
  File "D:\PyCharmProjects\Vouch Bot\.venv\lib\site-packages\discord\app_commands\commands.py", line 827, in _do_call
    return await self._callback(self.binding, interaction, **params)  # type: ignore
  File "D:\PyCharmProjects\Vouch Bot\commands.py", line 147, in promote
    await member.add_roles(role)
  File "D:\PyCharmProjects\Vouch Bot\.venv\lib\site-packages\discord\member.py", line 1051, in add_roles
    await req(guild_id, user_id, role.id, reason=reason)
AttributeError: 'NoneType' object has no attribute 'id'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\PyCharmProjects\Vouch Bot\.venv\lib\site-packages\discord\app_commands\tree.py", line 1248, in _call
    await command._invoke_with_namespace(interaction, namespace)
  File "D:\PyCharmProjects\Vouch Bot\.venv\lib\site-packages\discord\app_commands\commands.py", line 853, in _invoke_with_namespace
    return await self._do_call(interaction, transformed_values)
  File "D:\PyCharmProjects\Vouch Bot\.venv\lib\site-packages\discord\app_commands\commands.py", line 846, in _do_call
    raise CommandInvokeError(self, e) from e
discord.app_commands.errors.CommandInvokeError: Command 'promote' raised an exception: AttributeError: 'NoneType' object has no attribute 'id'
2024-01-23 20:42:29,833:WARNING:discord.client: PyNaCl is not installed, voice will NOT be supported
2024-01-23 20:42:29,851:INFO:discord.client: logging in using static token
2024-01-23 20:42:31,025:INFO:discord.gateway: Shard ID None has connected to Gateway (Session ID: 492ceb55b083278bcaaf0b3d6bdb15f3).
2024-01-23 20:44:29,346:WARNING:discord.client: PyNaCl is not installed, voice will NOT be supported
2024-01-23 20:44:29,359:INFO:discord.client: logging in using static token
2024-01-23 20:44:30,520:INFO:discord.gateway: Shard ID None has connected to Gateway (Session ID: f6fccb1f976482bd329fb6f58698a5e6).
2024-01-23 20:44:40,790:INFO:discord: Command: /promote shauuu_ Divisão 1 by shauuu_
2024-01-23 20:52:25,960:WARNING:discord.client: PyNaCl is not installed, voice will NOT be supported
2024-01-23 20:52:25,966:INFO:discord.client: logging in using static token
2024-01-23 20:52:27,091:INFO:discord.gateway: Shard ID None has connected to Gateway (Session ID: cf6a32b586c7dc68d126f760f98ba75e).
2024-01-23 20:52:50,401:INFO:discord: Command: /give_vouch shauuu_ teste by shauuu_
2024-01-23 20:53:04,579:INFO:discord: Command: /give_vouch shauuu_ teste by shauuu_
2024-01-23 20:53:40,878:WARNING:discord.client: PyNaCl is not installed, voice will NOT be supported
2024-01-23 20:53:40,883:INFO:discord.client: logging in using static token
2024-01-23 20:53:42,100:INFO:discord.gateway: Shard ID None has connected to Gateway (Session ID: 14c8f99693dda3853aedbd6cfaef946b).
2024-01-23 20:53:52,525:INFO:discord: Command: /give_vouch shauuu_ teste by shauuu_
2024-01-23 20:56:29,464:WARNING:discord.client: PyNaCl is not installed, voice will NOT be supported
2024-01-23 20:56:29,470:INFO:discord.client: logging in using static token
2024-01-23 20:56:30,623:INFO:discord.gateway: Shard ID None has connected to Gateway (Session ID: 181ad7d508e61cf5718fefc32d356572).
2024-01-23 20:56:40,934:INFO:discord: Command: /vouches shauuu_ Divisão 1 by shauuu_
2024-01-23 20:57:19,266:INFO:discord: Command: /give_vouch shauuu_ teste by shauuu_
2024-01-23 20:57:26,315:INFO:discord: Command: /vouches shauuu_ Divisão 2 by shauuu_
2024-01-23 21:38:13,596:WARNING:discord.client: PyNaCl is not installed, voice will NOT be supported
2024-01-23 21:38:13,610:INFO:discord.client: logging in using static token
2024-01-23 21:38:14,819:INFO:discord.gateway: Shard ID None has connected to Gateway (Session ID: dd99ab9a57b9925f6cf7622c5f4082b8).
2024-01-23 21:38:27,312:INFO:discord: Command: /give_vouch shauuu_ teste by shauuu_
2024-01-23 21:38:27,312:ERROR:discord.app_commands.tree: Ignoring exception in command 'give_vouch'
Traceback (most recent call last):
  File "D:\PyCharmProjects\Vouch Bot\.venv\lib\site-packages\discord\app_commands\commands.py", line 827, in _do_call
    return await self._callback(self.binding, interaction, **params)  # type: ignore
  File "D:\PyCharmProjects\Vouch Bot\commands.py", line 54, in give_vouch
    current_division = convert_role_to_name(ctx.guild.get_member(usuario.id))
  File "D:\PyCharmProjects\Vouch Bot\utils.py", line 50, in convert_role_to_name
    if role.id in div_roles.values():
AttributeError: 'list' object has no attribute 'values'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\PyCharmProjects\Vouch Bot\.venv\lib\site-packages\discord\app_commands\tree.py", line 1248, in _call
    await command._invoke_with_namespace(interaction, namespace)
  File "D:\PyCharmProjects\Vouch Bot\.venv\lib\site-packages\discord\app_commands\commands.py", line 853, in _invoke_with_namespace
    return await self._do_call(interaction, transformed_values)
  File "D:\PyCharmProjects\Vouch Bot\.venv\lib\site-packages\discord\app_commands\commands.py", line 846, in _do_call
    raise CommandInvokeError(self, e) from e
discord.app_commands.errors.CommandInvokeError: Command 'give_vouch' raised an exception: AttributeError: 'list' object has no attribute 'values'
2024-01-23 21:39:15,751:WARNING:discord.client: PyNaCl is not installed, voice will NOT be supported
2024-01-23 21:39:15,769:INFO:discord.client: logging in using static token
2024-01-23 21:39:16,845:INFO:discord.gateway: Shard ID None has connected to Gateway (Session ID: 014e6c16264d991175c2fa17193cd5d2).
2024-01-23 21:39:21,118:INFO:discord: Command: /give_vouch shauuu_ teste by shauuu_
2024-01-23 21:39:21,119:ERROR:discord.app_commands.tree: Ignoring exception in command 'give_vouch'
Traceback (most recent call last):
  File "D:\PyCharmProjects\Vouch Bot\.venv\lib\site-packages\discord\app_commands\commands.py", line 827, in _do_call
    return await self._callback(self.binding, interaction, **params)  # type: ignore
  File "D:\PyCharmProjects\Vouch Bot\commands.py", line 54, in give_vouch
    current_division = convert_role_to_name(ctx.guild.get_member(usuario.id))
  File "D:\PyCharmProjects\Vouch Bot\utils.py", line 50, in convert_role_to_name
    if role.id in div_roles.values():
AttributeError: 'list' object has no attribute 'values'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\PyCharmProjects\Vouch Bot\.venv\lib\site-packages\discord\app_commands\tree.py", line 1248, in _call
    await command._invoke_with_namespace(interaction, namespace)
  File "D:\PyCharmProjects\Vouch Bot\.venv\lib\site-packages\discord\app_commands\commands.py", line 853, in _invoke_with_namespace
    return await self._do_call(interaction, transformed_values)
  File "D:\PyCharmProjects\Vouch Bot\.venv\lib\site-packages\discord\app_commands\commands.py", line 846, in _do_call
    raise CommandInvokeError(self, e) from e
discord.app_commands.errors.CommandInvokeError: Command 'give_vouch' raised an exception: AttributeError: 'list' object has no attribute 'values'
2024-01-23 21:39:32,180:WARNING:discord.client: PyNaCl is not installed, voice will NOT be supported
2024-01-23 21:39:32,192:INFO:discord.client: logging in using static token
2024-01-23 21:39:33,276:INFO:discord.gateway: Shard ID None has connected to Gateway (Session ID: 28627afa8a473a1cd13fa8a1daa2b659).
2024-01-23 21:39:40,457:INFO:discord: Command: /give_vouch shauuu_ teste by shauuu_
2024-01-23 21:39:40,457:ERROR:discord.app_commands.tree: Ignoring exception in command 'give_vouch'
Traceback (most recent call last):
  File "D:\PyCharmProjects\Vouch Bot\.venv\lib\site-packages\discord\app_commands\commands.py", line 827, in _do_call
    return await self._callback(self.binding, interaction, **params)  # type: ignore
  File "D:\PyCharmProjects\Vouch Bot\commands.py", line 54, in give_vouch
    current_division = convert_role_to_name(ctx.guild.get_member(usuario.id))
  File "D:\PyCharmProjects\Vouch Bot\utils.py", line 50, in convert_role_to_name
    if role.id in div_roles.values():
AttributeError: 'list' object has no attribute 'values'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\PyCharmProjects\Vouch Bot\.venv\lib\site-packages\discord\app_commands\tree.py", line 1248, in _call
    await command._invoke_with_namespace(interaction, namespace)
  File "D:\PyCharmProjects\Vouch Bot\.venv\lib\site-packages\discord\app_commands\commands.py", line 853, in _invoke_with_namespace
    return await self._do_call(interaction, transformed_values)
  File "D:\PyCharmProjects\Vouch Bot\.venv\lib\site-packages\discord\app_commands\commands.py", line 846, in _do_call
    raise CommandInvokeError(self, e) from e
discord.app_commands.errors.CommandInvokeError: Command 'give_vouch' raised an exception: AttributeError: 'list' object has no attribute 'values'
2024-01-23 21:39:57,077:WARNING:discord.client: PyNaCl is not installed, voice will NOT be supported
2024-01-23 21:39:57,089:INFO:discord.client: logging in using static token
2024-01-23 21:39:59,673:INFO:discord.gateway: Shard ID None has connected to Gateway (Session ID: ff742523ce579335c12c0c97100199ae).
2024-01-23 21:40:03,225:INFO:discord: Command: /give_vouch shauuu_ teste by shauuu_
2024-01-23 21:40:03,225:ERROR:discord.app_commands.tree: Ignoring exception in command 'give_vouch'
Traceback (most recent call last):
  File "D:\PyCharmProjects\Vouch Bot\.venv\lib\site-packages\discord\app_commands\commands.py", line 827, in _do_call
    return await self._callback(self.binding, interaction, **params)  # type: ignore
  File "D:\PyCharmProjects\Vouch Bot\commands.py", line 55, in give_vouch
    current_division = convert_role_to_name(ctx.guild.get_member(usuario.id))
  File "D:\PyCharmProjects\Vouch Bot\utils.py", line 50, in convert_role_to_name
    if role.id in div_roles.values():
AttributeError: 'list' object has no attribute 'values'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\PyCharmProjects\Vouch Bot\.venv\lib\site-packages\discord\app_commands\tree.py", line 1248, in _call
    await command._invoke_with_namespace(interaction, namespace)
  File "D:\PyCharmProjects\Vouch Bot\.venv\lib\site-packages\discord\app_commands\commands.py", line 853, in _invoke_with_namespace
    return await self._do_call(interaction, transformed_values)
  File "D:\PyCharmProjects\Vouch Bot\.venv\lib\site-packages\discord\app_commands\commands.py", line 846, in _do_call
    raise CommandInvokeError(self, e) from e
discord.app_commands.errors.CommandInvokeError: Command 'give_vouch' raised an exception: AttributeError: 'list' object has no attribute 'values'
2024-01-23 21:40:27,953:WARNING:discord.client: PyNaCl is not installed, voice will NOT be supported
2024-01-23 21:40:27,967:INFO:discord.client: logging in using static token
2024-01-23 21:40:29,095:INFO:discord.gateway: Shard ID None has connected to Gateway (Session ID: e2e8f63d725fa85b57e82bbef2dcd46a).
2024-01-23 21:40:44,963:INFO:discord: Command: /give_vouch shauuu_ teste by shauuu_
2024-01-23 21:40:44,963:ERROR:discord.app_commands.tree: Ignoring exception in command 'give_vouch'
Traceback (most recent call last):
  File "D:\PyCharmProjects\Vouch Bot\.venv\lib\site-packages\discord\app_commands\commands.py", line 827, in _do_call
    return await self._callback(self.binding, interaction, **params)  # type: ignore
  File "D:\PyCharmProjects\Vouch Bot\commands.py", line 55, in give_vouch
    current_division = convert_role_to_name(ctx.guild.get_member(usuario.id))
  File "D:\PyCharmProjects\Vouch Bot\utils.py", line 50, in convert_role_to_name
    if role.id in div_roles.values():
AttributeError: 'list' object has no attribute 'values'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\PyCharmProjects\Vouch Bot\.venv\lib\site-packages\discord\app_commands\tree.py", line 1248, in _call
    await command._invoke_with_namespace(interaction, namespace)
  File "D:\PyCharmProjects\Vouch Bot\.venv\lib\site-packages\discord\app_commands\commands.py", line 853, in _invoke_with_namespace
    return await self._do_call(interaction, transformed_values)
  File "D:\PyCharmProjects\Vouch Bot\.venv\lib\site-packages\discord\app_commands\commands.py", line 846, in _do_call
    raise CommandInvokeError(self, e) from e
discord.app_commands.errors.CommandInvokeError: Command 'give_vouch' raised an exception: AttributeError: 'list' object has no attribute 'values'
2024-01-23 21:41:31,251:WARNING:discord.client: PyNaCl is not installed, voice will NOT be supported
2024-01-23 21:41:31,263:INFO:discord.client: logging in using static token
2024-01-23 21:41:32,511:INFO:discord.gateway: Shard ID None has connected to Gateway (Session ID: 4beca2fd77af167d7200dd4ec9db14f9).
2024-01-23 21:41:36,108:INFO:discord: Command: /give_vouch shauuu_ teste by shauuu_
2024-01-23 21:41:36,108:ERROR:discord.app_commands.tree: Ignoring exception in command 'give_vouch'
Traceback (most recent call last):
  File "D:\PyCharmProjects\Vouch Bot\.venv\lib\site-packages\discord\app_commands\commands.py", line 827, in _do_call
    return await self._callback(self.binding, interaction, **params)  # type: ignore
  File "D:\PyCharmProjects\Vouch Bot\commands.py", line 55, in give_vouch
    current_division = convert_role_to_name(ctx.guild.get_member(usuario.id))
  File "D:\PyCharmProjects\Vouch Bot\utils.py", line 50, in convert_role_to_name
    if role.id in div_roles.values():
AttributeError: 'list' object has no attribute 'values'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\PyCharmProjects\Vouch Bot\.venv\lib\site-packages\discord\app_commands\tree.py", line 1248, in _call
    await command._invoke_with_namespace(interaction, namespace)
  File "D:\PyCharmProjects\Vouch Bot\.venv\lib\site-packages\discord\app_commands\commands.py", line 853, in _invoke_with_namespace
    return await self._do_call(interaction, transformed_values)
  File "D:\PyCharmProjects\Vouch Bot\.venv\lib\site-packages\discord\app_commands\commands.py", line 846, in _do_call
    raise CommandInvokeError(self, e) from e
discord.app_commands.errors.CommandInvokeError: Command 'give_vouch' raised an exception: AttributeError: 'list' object has no attribute 'values'
2024-01-23 21:42:07,762:WARNING:discord.client: PyNaCl is not installed, voice will NOT be supported
2024-01-23 21:42:07,777:INFO:discord.client: logging in using static token
2024-01-23 21:42:09,243:INFO:discord.gateway: Shard ID None has connected to Gateway (Session ID: 6f9d7c497d14e589427ee38b3d1e534c).
2024-01-23 21:42:13,117:INFO:discord: Command: /give_vouch shauuu_ teste by shauuu_
2024-01-23 21:42:13,117:ERROR:discord.app_commands.tree: Ignoring exception in command 'give_vouch'
Traceback (most recent call last):
  File "D:\PyCharmProjects\Vouch Bot\.venv\lib\site-packages\discord\app_commands\commands.py", line 827, in _do_call
    return await self._callback(self.binding, interaction, **params)  # type: ignore
  File "D:\PyCharmProjects\Vouch Bot\commands.py", line 54, in give_vouch
    current_division = convert_role_to_name(ctx.guild.get_member(usuario.id))
  File "D:\PyCharmProjects\Vouch Bot\utils.py", line 50, in convert_role_to_name
    if role.id in div_roles.values():
AttributeError: 'list' object has no attribute 'values'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\PyCharmProjects\Vouch Bot\.venv\lib\site-packages\discord\app_commands\tree.py", line 1248, in _call
    await command._invoke_with_namespace(interaction, namespace)
  File "D:\PyCharmProjects\Vouch Bot\.venv\lib\site-packages\discord\app_commands\commands.py", line 853, in _invoke_with_namespace
    return await self._do_call(interaction, transformed_values)
  File "D:\PyCharmProjects\Vouch Bot\.venv\lib\site-packages\discord\app_commands\commands.py", line 846, in _do_call
    raise CommandInvokeError(self, e) from e
discord.app_commands.errors.CommandInvokeError: Command 'give_vouch' raised an exception: AttributeError: 'list' object has no attribute 'values'
2024-01-23 21:42:40,247:WARNING:discord.client: PyNaCl is not installed, voice will NOT be supported
2024-01-23 21:42:40,260:INFO:discord.client: logging in using static token
2024-01-23 21:42:41,437:INFO:discord.gateway: Shard ID None has connected to Gateway (Session ID: 52bdc004759aae240182e29fa241dbcf).
2024-01-23 21:42:46,975:INFO:discord: Command: /give_vouch shauuu_ teste by shauuu_
2024-01-23 21:42:46,975:ERROR:discord.app_commands.tree: Ignoring exception in command 'give_vouch'
Traceback (most recent call last):
  File "D:\PyCharmProjects\Vouch Bot\.venv\lib\site-packages\discord\app_commands\commands.py", line 827, in _do_call
    return await self._callback(self.binding, interaction, **params)  # type: ignore
  File "D:\PyCharmProjects\Vouch Bot\commands.py", line 54, in give_vouch
    current_division = convert_role_to_name(ctx.guild.get_member(usuario.id))
  File "D:\PyCharmProjects\Vouch Bot\utils.py", line 49, in convert_role_to_name
    if role.id in div_roles.values():
AttributeError: 'list' object has no attribute 'values'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\PyCharmProjects\Vouch Bot\.venv\lib\site-packages\discord\app_commands\tree.py", line 1248, in _call
    await command._invoke_with_namespace(interaction, namespace)
  File "D:\PyCharmProjects\Vouch Bot\.venv\lib\site-packages\discord\app_commands\commands.py", line 853, in _invoke_with_namespace
    return await self._do_call(interaction, transformed_values)
  File "D:\PyCharmProjects\Vouch Bot\.venv\lib\site-packages\discord\app_commands\commands.py", line 846, in _do_call
    raise CommandInvokeError(self, e) from e
discord.app_commands.errors.CommandInvokeError: Command 'give_vouch' raised an exception: AttributeError: 'list' object has no attribute 'values'
2024-01-23 21:42:56,058:WARNING:discord.client: PyNaCl is not installed, voice will NOT be supported
2024-01-23 21:42:56,069:INFO:discord.client: logging in using static token
2024-01-23 21:42:57,178:INFO:discord.gateway: Shard ID None has connected to Gateway (Session ID: 0d1f2eb1715dcc10c106fb2ffb84bf20).
2024-01-23 21:43:05,650:INFO:discord: Command: /give_vouch shauuu_ teste by shauuu_
2024-01-23 21:43:05,651:ERROR:discord.app_commands.tree: Ignoring exception in command 'give_vouch'
Traceback (most recent call last):
  File "D:\PyCharmProjects\Vouch Bot\.venv\lib\site-packages\discord\app_commands\commands.py", line 827, in _do_call
    return await self._callback(self.binding, interaction, **params)  # type: ignore
  File "D:\PyCharmProjects\Vouch Bot\commands.py", line 54, in give_vouch
    current_division = convert_role_to_name(ctx.guild.get_member(usuario.id))
  File "D:\PyCharmProjects\Vouch Bot\utils.py", line 50, in convert_role_to_name
    if role.id in div_roles.values():
AttributeError: 'list' object has no attribute 'values'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\PyCharmProjects\Vouch Bot\.venv\lib\site-packages\discord\app_commands\tree.py", line 1248, in _call
    await command._invoke_with_namespace(interaction, namespace)
  File "D:\PyCharmProjects\Vouch Bot\.venv\lib\site-packages\discord\app_commands\commands.py", line 853, in _invoke_with_namespace
    return await self._do_call(interaction, transformed_values)
  File "D:\PyCharmProjects\Vouch Bot\.venv\lib\site-packages\discord\app_commands\commands.py", line 846, in _do_call
    raise CommandInvokeError(self, e) from e
discord.app_commands.errors.CommandInvokeError: Command 'give_vouch' raised an exception: AttributeError: 'list' object has no attribute 'values'
2024-01-23 21:43:17,466:WARNING:discord.client: PyNaCl is not installed, voice will NOT be supported
2024-01-23 21:43:17,479:INFO:discord.client: logging in using static token
2024-01-23 21:43:18,494:INFO:discord.gateway: Shard ID None has connected to Gateway (Session ID: 88bdd5232160ab987796f7ad361c6a6c).
2024-01-23 21:46:43,084:WARNING:discord.client: PyNaCl is not installed, voice will NOT be supported
2024-01-23 21:46:43,095:INFO:discord.client: logging in using static token
2024-01-23 21:46:44,430:INFO:discord.gateway: Shard ID None has connected to Gateway (Session ID: e32e30d62a57f5f6f96b6ed720daa729).
2024-01-23 21:46:53,679:INFO:discord: Command: /give_vouch shauuu_ teste by shauuu_
2024-01-23 21:47:32,374:WARNING:discord.client: PyNaCl is not installed, voice will NOT be supported
2024-01-23 21:47:32,437:INFO:discord.client: logging in using static token
2024-01-23 21:47:33,521:INFO:discord.gateway: Shard ID None has connected to Gateway (Session ID: 8c85635d1c06d2441bcc4bf09a9806b1).
2024-01-23 21:47:44,585:INFO:discord: Command: /give_vouch shauuu_ teste by shauuu_
2024-01-23 21:47:58,336:INFO:discord: Command: /give_vouch shauuu_ teste by shauuu_
2024-01-23 22:12:36,936:WARNING:discord.client: PyNaCl is not installed, voice will NOT be supported
2024-01-23 22:12:36,955:INFO:discord.client: logging in using static token
2024-01-23 22:12:38,246:INFO:discord.gateway: Shard ID None has connected to Gateway (Session ID: 4c86a1ae9b25d7e15948c0da76128261).
2024-01-23 22:13:36,400:WARNING:discord.client: PyNaCl is not installed, voice will NOT be supported
2024-01-23 22:13:36,416:INFO:discord.client: logging in using static token
2024-01-23 22:13:37,604:INFO:discord.gateway: Shard ID None has connected to Gateway (Session ID: 5122efa214e9536c599c60f962e384e3).
2024-01-23 22:14:04,917:WARNING:discord.client: PyNaCl is not installed, voice will NOT be supported
2024-01-23 22:14:04,930:INFO:discord.client: logging in using static token
2024-01-23 22:14:06,052:INFO:discord.gateway: Shard ID None has connected to Gateway (Session ID: cdacc72f43c90d4abe8e48f221ee2f45).
2024-01-23 22:14:31,136:INFO:discord: Command: /vouches shauuu_ Divisão 1 by shauuu_
2024-01-23 22:14:31,139:ERROR:discord.app_commands.tree: Ignoring exception in command 'vouches'
Traceback (most recent call last):
  File "D:\PyCharmProjects\Vouch Bot\.venv\lib\site-packages\discord\app_commands\commands.py", line 827, in _do_call
    return await self._callback(self.binding, interaction, **params)  # type: ignore
  File "D:\PyCharmProjects\Vouch Bot\commands.py", line 100, in vouches
    if int(role_to_name.split(" ")[1]) < int(convert_role_to_name(Vouch.get_division_at_the_insertion(usuario.id, vouch_id)).split(" ")[1]):
  File "D:\PyCharmProjects\Vouch Bot\utils.py", line 47, in convert_role_to_name
    for role in member.roles:
AttributeError: 'str' object has no attribute 'roles'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\PyCharmProjects\Vouch Bot\.venv\lib\site-packages\discord\app_commands\tree.py", line 1248, in _call
    await command._invoke_with_namespace(interaction, namespace)
  File "D:\PyCharmProjects\Vouch Bot\.venv\lib\site-packages\discord\app_commands\commands.py", line 853, in _invoke_with_namespace
    return await self._do_call(interaction, transformed_values)
  File "D:\PyCharmProjects\Vouch Bot\.venv\lib\site-packages\discord\app_commands\commands.py", line 846, in _do_call
    raise CommandInvokeError(self, e) from e
discord.app_commands.errors.CommandInvokeError: Command 'vouches' raised an exception: AttributeError: 'str' object has no attribute 'roles'
2024-01-23 22:15:33,335:WARNING:discord.client: PyNaCl is not installed, voice will NOT be supported
2024-01-23 22:15:33,349:INFO:discord.client: logging in using static token
2024-01-23 22:15:34,457:INFO:discord.gateway: Shard ID None has connected to Gateway (Session ID: 60b3421c8eb122959981c8084d2d16c4).
2024-01-23 22:15:51,221:INFO:discord: Command: /give_vouch shauuu_ teste by shauuu_
2024-01-23 22:16:08,053:INFO:discord: Command: /vouches shauuu_ Divisão 1 by shauuu_
2024-01-23 22:16:08,056:ERROR:discord.app_commands.tree: Ignoring exception in command 'vouches'
Traceback (most recent call last):
  File "D:\PyCharmProjects\Vouch Bot\.venv\lib\site-packages\discord\app_commands\commands.py", line 827, in _do_call
    return await self._callback(self.binding, interaction, **params)  # type: ignore
  File "D:\PyCharmProjects\Vouch Bot\commands.py", line 98, in vouches
    if int(rank.split(" ")[1]) < int(convert_role_to_name(Vouch.get_division_at_the_insertion(usuario.id, vouch_id)).split(" ")[1]):
AttributeError: 'Choice' object has no attribute 'split'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\PyCharmProjects\Vouch Bot\.venv\lib\site-packages\discord\app_commands\tree.py", line 1248, in _call
    await command._invoke_with_namespace(interaction, namespace)
  File "D:\PyCharmProjects\Vouch Bot\.venv\lib\site-packages\discord\app_commands\commands.py", line 853, in _invoke_with_namespace
    return await self._do_call(interaction, transformed_values)
  File "D:\PyCharmProjects\Vouch Bot\.venv\lib\site-packages\discord\app_commands\commands.py", line 846, in _do_call
    raise CommandInvokeError(self, e) from e
discord.app_commands.errors.CommandInvokeError: Command 'vouches' raised an exception: AttributeError: 'Choice' object has no attribute 'split'
2024-01-23 22:16:52,628:WARNING:discord.client: PyNaCl is not installed, voice will NOT be supported
2024-01-23 22:16:52,642:INFO:discord.client: logging in using static token
2024-01-23 22:16:53,864:INFO:discord.gateway: Shard ID None has connected to Gateway (Session ID: c043c7a9e7a7a8bff59bb2f9af9e13a9).
2024-01-23 22:17:00,395:INFO:discord: Command: /vouches shauuu_ Divisão 1 by shauuu_
2024-01-23 22:17:00,397:ERROR:discord.app_commands.tree: Ignoring exception in command 'vouches'
Traceback (most recent call last):
  File "D:\PyCharmProjects\Vouch Bot\.venv\lib\site-packages\discord\app_commands\commands.py", line 827, in _do_call
    return await self._callback(self.binding, interaction, **params)  # type: ignore
  File "D:\PyCharmProjects\Vouch Bot\commands.py", line 97, in vouches
    print(int(rank.split(" ")[1]) < int(convert_role_to_name(Vouch.get_division_at_the_insertion(usuario.id, vouch_id)).split(" ")[1]))
AttributeError: 'Choice' object has no attribute 'split'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\PyCharmProjects\Vouch Bot\.venv\lib\site-packages\discord\app_commands\tree.py", line 1248, in _call
    await command._invoke_with_namespace(interaction, namespace)
  File "D:\PyCharmProjects\Vouch Bot\.venv\lib\site-packages\discord\app_commands\commands.py", line 853, in _invoke_with_namespace
    return await self._do_call(interaction, transformed_values)
  File "D:\PyCharmProjects\Vouch Bot\.venv\lib\site-packages\discord\app_commands\commands.py", line 846, in _do_call
    raise CommandInvokeError(self, e) from e
discord.app_commands.errors.CommandInvokeError: Command 'vouches' raised an exception: AttributeError: 'Choice' object has no attribute 'split'
2024-01-23 22:17:09,639:WARNING:discord.client: PyNaCl is not installed, voice will NOT be supported
2024-01-23 22:17:09,653:INFO:discord.client: logging in using static token
2024-01-23 22:17:10,775:INFO:discord.gateway: Shard ID None has connected to Gateway (Session ID: dec48986bd787965fc08ae809b078924).
2024-01-23 22:17:18,710:INFO:discord: Command: /vouches shauuu_ Divisão 1 by shauuu_
2024-01-23 22:17:18,712:ERROR:discord.app_commands.tree: Ignoring exception in command 'vouches'
Traceback (most recent call last):
  File "D:\PyCharmProjects\Vouch Bot\.venv\lib\site-packages\discord\app_commands\commands.py", line 827, in _do_call
    return await self._callback(self.binding, interaction, **params)  # type: ignore
  File "D:\PyCharmProjects\Vouch Bot\commands.py", line 99, in vouches
    if int(rank.split(" ")[1]) < int(convert_role_to_name(Vouch.get_division_at_the_insertion(usuario.id, vouch_id)).split(" ")[1]):
AttributeError: 'Choice' object has no attribute 'split'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\PyCharmProjects\Vouch Bot\.venv\lib\site-packages\discord\app_commands\tree.py", line 1248, in _call
    await command._invoke_with_namespace(interaction, namespace)
  File "D:\PyCharmProjects\Vouch Bot\.venv\lib\site-packages\discord\app_commands\commands.py", line 853, in _invoke_with_namespace
    return await self._do_call(interaction, transformed_values)
  File "D:\PyCharmProjects\Vouch Bot\.venv\lib\site-packages\discord\app_commands\commands.py", line 846, in _do_call
    raise CommandInvokeError(self, e) from e
discord.app_commands.errors.CommandInvokeError: Command 'vouches' raised an exception: AttributeError: 'Choice' object has no attribute 'split'
2024-01-23 22:17:55,461:WARNING:discord.client: PyNaCl is not installed, voice will NOT be supported
2024-01-23 22:17:55,475:INFO:discord.client: logging in using static token
2024-01-23 22:17:56,756:INFO:discord.gateway: Shard ID None has connected to Gateway (Session ID: b96a27fe3de42cc4231b2a6416da3ec5).
2024-01-23 22:18:01,830:INFO:discord: Command: /vouches shauuu_ Divisão 1 by shauuu_
2024-01-23 22:18:01,832:ERROR:discord.app_commands.tree: Ignoring exception in command 'vouches'
Traceback (most recent call last):
  File "D:\PyCharmProjects\Vouch Bot\.venv\lib\site-packages\discord\app_commands\commands.py", line 827, in _do_call
    return await self._callback(self.binding, interaction, **params)  # type: ignore
  File "D:\PyCharmProjects\Vouch Bot\commands.py", line 98, in vouches
    print(rank.split(" "))
AttributeError: 'Choice' object has no attribute 'split'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\PyCharmProjects\Vouch Bot\.venv\lib\site-packages\discord\app_commands\tree.py", line 1248, in _call
    await command._invoke_with_namespace(interaction, namespace)
  File "D:\PyCharmProjects\Vouch Bot\.venv\lib\site-packages\discord\app_commands\commands.py", line 853, in _invoke_with_namespace
    return await self._do_call(interaction, transformed_values)
  File "D:\PyCharmProjects\Vouch Bot\.venv\lib\site-packages\discord\app_commands\commands.py", line 846, in _do_call
    raise CommandInvokeError(self, e) from e
discord.app_commands.errors.CommandInvokeError: Command 'vouches' raised an exception: AttributeError: 'Choice' object has no attribute 'split'
2024-01-23 22:18:07,934:WARNING:discord.client: PyNaCl is not installed, voice will NOT be supported
2024-01-23 22:18:07,947:INFO:discord.client: logging in using static token
2024-01-23 22:18:09,198:INFO:discord.gateway: Shard ID None has connected to Gateway (Session ID: 24d3dbfcfb368faff652d667782553a2).
2024-01-23 22:18:12,787:INFO:discord: Command: /vouches shauuu_ Divisão 1 by shauuu_
2024-01-23 22:18:12,789:ERROR:discord.app_commands.tree: Ignoring exception in command 'vouches'
Traceback (most recent call last):
  File "D:\PyCharmProjects\Vouch Bot\.venv\lib\site-packages\discord\app_commands\commands.py", line 827, in _do_call
    return await self._callback(self.binding, interaction, **params)  # type: ignore
  File "D:\PyCharmProjects\Vouch Bot\commands.py", line 99, in vouches
    if int(rank.split(" ")[1]) < int(convert_role_to_name(Vouch.get_division_at_the_insertion(usuario.id, vouch_id)).split(" ")[1]):
AttributeError: 'Choice' object has no attribute 'split'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\PyCharmProjects\Vouch Bot\.venv\lib\site-packages\discord\app_commands\tree.py", line 1248, in _call
    await command._invoke_with_namespace(interaction, namespace)
  File "D:\PyCharmProjects\Vouch Bot\.venv\lib\site-packages\discord\app_commands\commands.py", line 853, in _invoke_with_namespace
    return await self._do_call(interaction, transformed_values)
  File "D:\PyCharmProjects\Vouch Bot\.venv\lib\site-packages\discord\app_commands\commands.py", line 846, in _do_call
    raise CommandInvokeError(self, e) from e
discord.app_commands.errors.CommandInvokeError: Command 'vouches' raised an exception: AttributeError: 'Choice' object has no attribute 'split'
2024-01-23 22:18:32,436:WARNING:discord.client: PyNaCl is not installed, voice will NOT be supported
2024-01-23 22:18:32,449:INFO:discord.client: logging in using static token
2024-01-23 22:18:33,574:INFO:discord.gateway: Shard ID None has connected to Gateway (Session ID: 6833c5f02cda9a62622411c6cec3e062).
2024-01-23 22:18:43,165:INFO:discord: Command: /vouches shauuu_ Divisão 1 by shauuu_
2024-01-23 22:18:43,168:ERROR:discord.app_commands.tree: Ignoring exception in command 'vouches'
Traceback (most recent call last):
  File "D:\PyCharmProjects\Vouch Bot\.venv\lib\site-packages\discord\app_commands\commands.py", line 827, in _do_call
    return await self._callback(self.binding, interaction, **params)  # type: ignore
  File "D:\PyCharmProjects\Vouch Bot\commands.py", line 98, in vouches
    if int(rank.name.split(" ")[1]) < int(convert_role_to_name(Vouch.get_division_at_the_insertion(usuario.id, vouch_id)).split(" ")[1]):
  File "D:\PyCharmProjects\Vouch Bot\utils.py", line 47, in convert_role_to_name
    for role in member.roles:
AttributeError: 'str' object has no attribute 'roles'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\PyCharmProjects\Vouch Bot\.venv\lib\site-packages\discord\app_commands\tree.py", line 1248, in _call
    await command._invoke_with_namespace(interaction, namespace)
  File "D:\PyCharmProjects\Vouch Bot\.venv\lib\site-packages\discord\app_commands\commands.py", line 853, in _invoke_with_namespace
    return await self._do_call(interaction, transformed_values)
  File "D:\PyCharmProjects\Vouch Bot\.venv\lib\site-packages\discord\app_commands\commands.py", line 846, in _do_call
    raise CommandInvokeError(self, e) from e
discord.app_commands.errors.CommandInvokeError: Command 'vouches' raised an exception: AttributeError: 'str' object has no attribute 'roles'
2024-01-23 22:18:56,346:WARNING:discord.client: PyNaCl is not installed, voice will NOT be supported
2024-01-23 22:18:56,359:INFO:discord.client: logging in using static token
2024-01-23 22:18:57,495:INFO:discord.gateway: Shard ID None has connected to Gateway (Session ID: 9e5d720033fe63502d6636c0e06cb370).
2024-01-23 22:19:06,403:INFO:discord: Command: /vouches shauuu_ Divisão 1 by shauuu_
2024-01-23 22:19:06,405:ERROR:discord.app_commands.tree: Ignoring exception in command 'vouches'
Traceback (most recent call last):
  File "D:\PyCharmProjects\Vouch Bot\.venv\lib\site-packages\discord\app_commands\commands.py", line 827, in _do_call
    return await self._callback(self.binding, interaction, **params)  # type: ignore
  File "D:\PyCharmProjects\Vouch Bot\commands.py", line 99, in vouches
    if int(rank.name.split(" ")[1]) < int(convert_role_to_name(Vouch.get_division_at_the_insertion(usuario.id, vouch_id)).split(" ")[1]):
  File "D:\PyCharmProjects\Vouch Bot\utils.py", line 47, in convert_role_to_name
    for role in member.roles:
AttributeError: 'str' object has no attribute 'roles'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\PyCharmProjects\Vouch Bot\.venv\lib\site-packages\discord\app_commands\tree.py", line 1248, in _call
    await command._invoke_with_namespace(interaction, namespace)
  File "D:\PyCharmProjects\Vouch Bot\.venv\lib\site-packages\discord\app_commands\commands.py", line 853, in _invoke_with_namespace
    return await self._do_call(interaction, transformed_values)
  File "D:\PyCharmProjects\Vouch Bot\.venv\lib\site-packages\discord\app_commands\commands.py", line 846, in _do_call
    raise CommandInvokeError(self, e) from e
discord.app_commands.errors.CommandInvokeError: Command 'vouches' raised an exception: AttributeError: 'str' object has no attribute 'roles'
2024-01-23 22:19:18,782:WARNING:discord.client: PyNaCl is not installed, voice will NOT be supported
2024-01-23 22:19:18,796:INFO:discord.client: logging in using static token
2024-01-23 22:19:19,932:INFO:discord.gateway: Shard ID None has connected to Gateway (Session ID: 0fd7f2fc6421c2bc01adfadc601cb90e).
2024-01-23 22:19:22,186:WARNING:discord.http: We are being rate limited. PUT https://discord.com/api/v10/applications/1198496806124933190/commands responded with 429. Retrying in 6.90 seconds.
2024-01-23 22:19:28,643:INFO:discord: Command: /vouches shauuu_ Divisão 1 by shauuu_
2024-01-23 22:19:28,646:ERROR:discord.app_commands.tree: Ignoring exception in command 'vouches'
Traceback (most recent call last):
  File "D:\PyCharmProjects\Vouch Bot\.venv\lib\site-packages\discord\app_commands\commands.py", line 827, in _do_call
    return await self._callback(self.binding, interaction, **params)  # type: ignore
  File "D:\PyCharmProjects\Vouch Bot\commands.py", line 99, in vouches
    if int(rank.name.split(" ")[1]) < int(convert_role_to_name(Vouch.get_division_at_the_insertion(usuario.id, vouch_id)).split(" ")[1]):
  File "D:\PyCharmProjects\Vouch Bot\utils.py", line 47, in convert_role_to_name
    for role in member.roles:
AttributeError: 'str' object has no attribute 'roles'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\PyCharmProjects\Vouch Bot\.venv\lib\site-packages\discord\app_commands\tree.py", line 1248, in _call
    await command._invoke_with_namespace(interaction, namespace)
  File "D:\PyCharmProjects\Vouch Bot\.venv\lib\site-packages\discord\app_commands\commands.py", line 853, in _invoke_with_namespace
    return await self._do_call(interaction, transformed_values)
  File "D:\PyCharmProjects\Vouch Bot\.venv\lib\site-packages\discord\app_commands\commands.py", line 846, in _do_call
    raise CommandInvokeError(self, e) from e
discord.app_commands.errors.CommandInvokeError: Command 'vouches' raised an exception: AttributeError: 'str' object has no attribute 'roles'
2024-01-23 22:20:24,567:WARNING:discord.client: PyNaCl is not installed, voice will NOT be supported
2024-01-23 22:20:24,580:INFO:discord.client: logging in using static token
2024-01-23 22:20:25,856:INFO:discord.gateway: Shard ID None has connected to Gateway (Session ID: 5c1f9cd9f4153f7ad5bf9883d839e01c).
2024-01-23 22:20:32,401:INFO:discord: Command: /vouches shauuu_ Divisão 1 by shauuu_
2024-01-23 22:20:32,404:ERROR:discord.app_commands.tree: Ignoring exception in command 'vouches'
Traceback (most recent call last):
  File "D:\PyCharmProjects\Vouch Bot\.venv\lib\site-packages\discord\app_commands\commands.py", line 827, in _do_call
    return await self._callback(self.binding, interaction, **params)  # type: ignore
  File "D:\PyCharmProjects\Vouch Bot\commands.py", line 99, in vouches
    print(convert_role_to_name(Vouch.get_division_at_the_insertion(usuario.id, vouch_id)))
  File "D:\PyCharmProjects\Vouch Bot\utils.py", line 47, in convert_role_to_name
    for role in member.roles:
AttributeError: 'str' object has no attribute 'roles'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\PyCharmProjects\Vouch Bot\.venv\lib\site-packages\discord\app_commands\tree.py", line 1248, in _call
    await command._invoke_with_namespace(interaction, namespace)
  File "D:\PyCharmProjects\Vouch Bot\.venv\lib\site-packages\discord\app_commands\commands.py", line 853, in _invoke_with_namespace
    return await self._do_call(interaction, transformed_values)
  File "D:\PyCharmProjects\Vouch Bot\.venv\lib\site-packages\discord\app_commands\commands.py", line 846, in _do_call
    raise CommandInvokeError(self, e) from e
discord.app_commands.errors.CommandInvokeError: Command 'vouches' raised an exception: AttributeError: 'str' object has no attribute 'roles'
2024-01-23 22:21:08,323:WARNING:discord.client: PyNaCl is not installed, voice will NOT be supported
2024-01-23 22:21:08,336:INFO:discord.client: logging in using static token
2024-01-23 22:21:09,478:INFO:discord.gateway: Shard ID None has connected to Gateway (Session ID: 1750403c0b62292c688fd9f63565594f).
2024-01-23 22:21:19,646:INFO:discord: Command: /vouches shauuu_ Divisão 1 by shauuu_
2024-01-23 22:21:19,648:ERROR:discord.app_commands.tree: Ignoring exception in command 'vouches'
Traceback (most recent call last):
  File "D:\PyCharmProjects\Vouch Bot\.venv\lib\site-packages\discord\app_commands\commands.py", line 827, in _do_call
    return await self._callback(self.binding, interaction, **params)  # type: ignore
  File "D:\PyCharmProjects\Vouch Bot\commands.py", line 104, in vouches
    if embed.fields.len() == 0:
AttributeError: 'list' object has no attribute 'len'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\PyCharmProjects\Vouch Bot\.venv\lib\site-packages\discord\app_commands\tree.py", line 1248, in _call
    await command._invoke_with_namespace(interaction, namespace)
  File "D:\PyCharmProjects\Vouch Bot\.venv\lib\site-packages\discord\app_commands\commands.py", line 853, in _invoke_with_namespace
    return await self._do_call(interaction, transformed_values)
  File "D:\PyCharmProjects\Vouch Bot\.venv\lib\site-packages\discord\app_commands\commands.py", line 846, in _do_call
    raise CommandInvokeError(self, e) from e
discord.app_commands.errors.CommandInvokeError: Command 'vouches' raised an exception: AttributeError: 'list' object has no attribute 'len'
2024-01-23 22:21:52,993:WARNING:discord.client: PyNaCl is not installed, voice will NOT be supported
2024-01-23 22:21:53,007:INFO:discord.client: logging in using static token
2024-01-23 22:21:54,144:INFO:discord.gateway: Shard ID None has connected to Gateway (Session ID: ae4f9afaadd9e3b59e5f983beaf462c7).
2024-01-23 22:21:58,194:INFO:discord: Command: /vouches shauuu_ Divisão 1 by shauuu_
2024-01-23 22:21:58,196:ERROR:discord.app_commands.tree: Ignoring exception in command 'vouches'
Traceback (most recent call last):
  File "D:\PyCharmProjects\Vouch Bot\.venv\lib\site-packages\discord\app_commands\commands.py", line 827, in _do_call
    return await self._callback(self.binding, interaction, **params)  # type: ignore
  File "D:\PyCharmProjects\Vouch Bot\commands.py", line 106, in vouches
    if embed.fields.len() == 0:
AttributeError: 'list' object has no attribute 'len'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\PyCharmProjects\Vouch Bot\.venv\lib\site-packages\discord\app_commands\tree.py", line 1248, in _call
    await command._invoke_with_namespace(interaction, namespace)
  File "D:\PyCharmProjects\Vouch Bot\.venv\lib\site-packages\discord\app_commands\commands.py", line 853, in _invoke_with_namespace
    return await self._do_call(interaction, transformed_values)
  File "D:\PyCharmProjects\Vouch Bot\.venv\lib\site-packages\discord\app_commands\commands.py", line 846, in _do_call
    raise CommandInvokeError(self, e) from e
discord.app_commands.errors.CommandInvokeError: Command 'vouches' raised an exception: AttributeError: 'list' object has no attribute 'len'
2024-01-23 22:22:06,593:WARNING:discord.client: PyNaCl is not installed, voice will NOT be supported
2024-01-23 22:22:06,608:INFO:discord.client: logging in using static token
2024-01-23 22:22:07,808:INFO:discord.gateway: Shard ID None has connected to Gateway (Session ID: d082a08b1149acb1b53da5241cb8efe4).
2024-01-23 22:22:11,215:INFO:discord: Command: /vouches shauuu_ Divisão 1 by shauuu_
2024-01-23 22:22:11,218:ERROR:discord.app_commands.tree: Ignoring exception in command 'vouches'
Traceback (most recent call last):
  File "D:\PyCharmProjects\Vouch Bot\.venv\lib\site-packages\discord\app_commands\commands.py", line 827, in _do_call
    return await self._callback(self.binding, interaction, **params)  # type: ignore
  File "D:\PyCharmProjects\Vouch Bot\commands.py", line 106, in vouches
    if embed.fields.len() == 0:
AttributeError: 'list' object has no attribute 'len'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\PyCharmProjects\Vouch Bot\.venv\lib\site-packages\discord\app_commands\tree.py", line 1248, in _call
    await command._invoke_with_namespace(interaction, namespace)
  File "D:\PyCharmProjects\Vouch Bot\.venv\lib\site-packages\discord\app_commands\commands.py", line 853, in _invoke_with_namespace
    return await self._do_call(interaction, transformed_values)
  File "D:\PyCharmProjects\Vouch Bot\.venv\lib\site-packages\discord\app_commands\commands.py", line 846, in _do_call
    raise CommandInvokeError(self, e) from e
discord.app_commands.errors.CommandInvokeError: Command 'vouches' raised an exception: AttributeError: 'list' object has no attribute 'len'
2024-01-23 22:22:24,736:WARNING:discord.client: PyNaCl is not installed, voice will NOT be supported
2024-01-23 22:22:24,751:INFO:discord.client: logging in using static token
2024-01-23 22:22:25,948:INFO:discord.gateway: Shard ID None has connected to Gateway (Session ID: d52869a88eac937d30141bdacdd4bd27).
2024-01-23 22:22:29,800:INFO:discord: Command: /vouches shauuu_ Divisão 1 by shauuu_
2024-01-23 22:22:29,803:ERROR:discord.app_commands.tree: Ignoring exception in command 'vouches'
Traceback (most recent call last):
  File "D:\PyCharmProjects\Vouch Bot\.venv\lib\site-packages\discord\app_commands\commands.py", line 827, in _do_call
    return await self._callback(self.binding, interaction, **params)  # type: ignore
  File "D:\PyCharmProjects\Vouch Bot\commands.py", line 106, in vouches
    if embed.fields.len() == 0:
AttributeError: 'list' object has no attribute 'len'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\PyCharmProjects\Vouch Bot\.venv\lib\site-packages\discord\app_commands\tree.py", line 1248, in _call
    await command._invoke_with_namespace(interaction, namespace)
  File "D:\PyCharmProjects\Vouch Bot\.venv\lib\site-packages\discord\app_commands\commands.py", line 853, in _invoke_with_namespace
    return await self._do_call(interaction, transformed_values)
  File "D:\PyCharmProjects\Vouch Bot\.venv\lib\site-packages\discord\app_commands\commands.py", line 846, in _do_call
    raise CommandInvokeError(self, e) from e
discord.app_commands.errors.CommandInvokeError: Command 'vouches' raised an exception: AttributeError: 'list' object has no attribute 'len'
2024-01-23 22:24:44,199:WARNING:discord.client: PyNaCl is not installed, voice will NOT be supported
2024-01-23 22:24:44,212:INFO:discord.client: logging in using static token
2024-01-23 22:24:45,376:INFO:discord.gateway: Shard ID None has connected to Gateway (Session ID: 26b588e6f970b463b524a12589977bd2).
2024-01-23 22:24:48,914:INFO:discord: Command: /vouches shauuu_ Divisão 1 by shauuu_
2024-01-23 22:24:48,916:ERROR:discord.app_commands.tree: Ignoring exception in command 'vouches'
Traceback (most recent call last):
  File "D:\PyCharmProjects\Vouch Bot\.venv\lib\site-packages\discord\app_commands\commands.py", line 827, in _do_call
    return await self._callback(self.binding, interaction, **params)  # type: ignore
  File "D:\PyCharmProjects\Vouch Bot\commands.py", line 103, in vouches
    value=f"Concedido por {attributed_by_user.mention} por {Vouch.get_description(usuario.id, vouch_id)}",
  File "D:\PyCharmProjects\Vouch Bot\vouch.py", line 33, in get_description
    return int(Vouch.loaded_vouches[str(user_id)][vouch_id]["description"])
ValueError: invalid literal for int() with base 10: 'teste'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\PyCharmProjects\Vouch Bot\.venv\lib\site-packages\discord\app_commands\tree.py", line 1248, in _call
    await command._invoke_with_namespace(interaction, namespace)
  File "D:\PyCharmProjects\Vouch Bot\.venv\lib\site-packages\discord\app_commands\commands.py", line 853, in _invoke_with_namespace
    return await self._do_call(interaction, transformed_values)
  File "D:\PyCharmProjects\Vouch Bot\.venv\lib\site-packages\discord\app_commands\commands.py", line 846, in _do_call
    raise CommandInvokeError(self, e) from e
discord.app_commands.errors.CommandInvokeError: Command 'vouches' raised an exception: ValueError: invalid literal for int() with base 10: 'teste'
2024-01-23 22:25:31,317:WARNING:discord.client: PyNaCl is not installed, voice will NOT be supported
2024-01-23 22:25:31,330:INFO:discord.client: logging in using static token
2024-01-23 22:25:32,386:INFO:discord.gateway: Shard ID None has connected to Gateway (Session ID: 69e9a9b98a39f64e3aaa7ce6d9b0b87b).
2024-01-23 22:25:38,751:INFO:discord: Command: /vouches shauuu_ Divisão 1 by shauuu_
2024-01-23 22:25:38,753:ERROR:discord.app_commands.tree: Ignoring exception in command 'vouches'
Traceback (most recent call last):
  File "D:\PyCharmProjects\Vouch Bot\.venv\lib\site-packages\discord\app_commands\commands.py", line 827, in _do_call
    return await self._callback(self.binding, interaction, **params)  # type: ignore
  File "D:\PyCharmProjects\Vouch Bot\commands.py", line 104, in vouches
    value=f"Concedido por {attributed_by_user.mention} por {Vouch.get_description(usuario.id, vouch_id)}",
  File "D:\PyCharmProjects\Vouch Bot\vouch.py", line 33, in get_description
    return int(Vouch.loaded_vouches[str(user_id)][vouch_id]["description"])
ValueError: invalid literal for int() with base 10: 'teste'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\PyCharmProjects\Vouch Bot\.venv\lib\site-packages\discord\app_commands\tree.py", line 1248, in _call
    await command._invoke_with_namespace(interaction, namespace)
  File "D:\PyCharmProjects\Vouch Bot\.venv\lib\site-packages\discord\app_commands\commands.py", line 853, in _invoke_with_namespace
    return await self._do_call(interaction, transformed_values)
  File "D:\PyCharmProjects\Vouch Bot\.venv\lib\site-packages\discord\app_commands\commands.py", line 846, in _do_call
    raise CommandInvokeError(self, e) from e
discord.app_commands.errors.CommandInvokeError: Command 'vouches' raised an exception: ValueError: invalid literal for int() with base 10: 'teste'
2024-01-23 22:26:24,670:WARNING:discord.client: PyNaCl is not installed, voice will NOT be supported
2024-01-23 22:26:24,685:INFO:discord.client: logging in using static token
2024-01-23 22:26:25,887:INFO:discord.gateway: Shard ID None has connected to Gateway (Session ID: 984fef4627dfb6c2081b1f7ec94eef67).
2024-01-23 22:26:29,824:INFO:discord: Command: /vouches shauuu_ Divisão 1 by shauuu_
2024-01-23 22:26:29,826:ERROR:discord.app_commands.tree: Ignoring exception in command 'vouches'
Traceback (most recent call last):
  File "D:\PyCharmProjects\Vouch Bot\.venv\lib\site-packages\discord\app_commands\commands.py", line 827, in _do_call
    return await self._callback(self.binding, interaction, **params)  # type: ignore
  File "D:\PyCharmProjects\Vouch Bot\commands.py", line 103, in vouches
    value=f"Concedido por {attributed_by_user.mention} por {Vouch.get_description(usuario.id, vouch_id)}",
  File "D:\PyCharmProjects\Vouch Bot\vouch.py", line 33, in get_description
    return int(Vouch.loaded_vouches[str(user_id)][vouch_id]["description"])
ValueError: invalid literal for int() with base 10: 'teste'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\PyCharmProjects\Vouch Bot\.venv\lib\site-packages\discord\app_commands\tree.py", line 1248, in _call
    await command._invoke_with_namespace(interaction, namespace)
  File "D:\PyCharmProjects\Vouch Bot\.venv\lib\site-packages\discord\app_commands\commands.py", line 853, in _invoke_with_namespace
    return await self._do_call(interaction, transformed_values)
  File "D:\PyCharmProjects\Vouch Bot\.venv\lib\site-packages\discord\app_commands\commands.py", line 846, in _do_call
    raise CommandInvokeError(self, e) from e
discord.app_commands.errors.CommandInvokeError: Command 'vouches' raised an exception: ValueError: invalid literal for int() with base 10: 'teste'
2024-01-23 22:27:05,922:WARNING:discord.client: PyNaCl is not installed, voice will NOT be supported
2024-01-23 22:27:05,937:INFO:discord.client: logging in using static token
2024-01-23 22:27:07,096:INFO:discord.gateway: Shard ID None has connected to Gateway (Session ID: cf595249237269aaed1279f05589d163).
2024-01-23 22:27:16,150:INFO:discord: Command: /vouches shauuu_ Divisão 1 by shauuu_
2024-01-23 22:27:16,153:ERROR:discord.app_commands.tree: Ignoring exception in command 'vouches'
Traceback (most recent call last):
  File "D:\PyCharmProjects\Vouch Bot\.venv\lib\site-packages\discord\app_commands\commands.py", line 827, in _do_call
    return await self._callback(self.binding, interaction, **params)  # type: ignore
  File "D:\PyCharmProjects\Vouch Bot\commands.py", line 98, in vouches
    print(Vouch.get_description(usuario.id, vouch_id))
  File "D:\PyCharmProjects\Vouch Bot\vouch.py", line 33, in get_description
    return int(Vouch.loaded_vouches[str(user_id)][vouch_id]["description"])
ValueError: invalid literal for int() with base 10: 'teste'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\PyCharmProjects\Vouch Bot\.venv\lib\site-packages\discord\app_commands\tree.py", line 1248, in _call
    await command._invoke_with_namespace(interaction, namespace)
  File "D:\PyCharmProjects\Vouch Bot\.venv\lib\site-packages\discord\app_commands\commands.py", line 853, in _invoke_with_namespace
    return await self._do_call(interaction, transformed_values)
  File "D:\PyCharmProjects\Vouch Bot\.venv\lib\site-packages\discord\app_commands\commands.py", line 846, in _do_call
    raise CommandInvokeError(self, e) from e
discord.app_commands.errors.CommandInvokeError: Command 'vouches' raised an exception: ValueError: invalid literal for int() with base 10: 'teste'
2024-01-23 22:28:15,032:WARNING:discord.client: PyNaCl is not installed, voice will NOT be supported
2024-01-23 22:28:15,039:INFO:discord.client: logging in using static token
2024-01-23 22:28:16,206:INFO:discord.gateway: Shard ID None has connected to Gateway (Session ID: d07c1a3985d310a23ca04fc66bcd34ea).
2024-01-23 22:28:25,081:INFO:discord: Command: /vouches shauuu_ Divisão 1 by shauuu_
2024-01-23 22:28:25,083:ERROR:discord.app_commands.tree: Ignoring exception in command 'vouches'
Traceback (most recent call last):
  File "D:\PyCharmProjects\Vouch Bot\.venv\lib\site-packages\discord\app_commands\commands.py", line 827, in _do_call
    return await self._callback(self.binding, interaction, **params)  # type: ignore
  File "D:\PyCharmProjects\Vouch Bot\commands.py", line 105, in vouches
    if embed.fields.len() == 0:
AttributeError: 'list' object has no attribute 'len'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\PyCharmProjects\Vouch Bot\.venv\lib\site-packages\discord\app_commands\tree.py", line 1248, in _call
    await command._invoke_with_namespace(interaction, namespace)
  File "D:\PyCharmProjects\Vouch Bot\.venv\lib\site-packages\discord\app_commands\commands.py", line 853, in _invoke_with_namespace
    return await self._do_call(interaction, transformed_values)
  File "D:\PyCharmProjects\Vouch Bot\.venv\lib\site-packages\discord\app_commands\commands.py", line 846, in _do_call
    raise CommandInvokeError(self, e) from e
discord.app_commands.errors.CommandInvokeError: Command 'vouches' raised an exception: AttributeError: 'list' object has no attribute 'len'
2024-01-23 22:28:55,962:WARNING:discord.client: PyNaCl is not installed, voice will NOT be supported
2024-01-23 22:28:55,985:INFO:discord.client: logging in using static token
2024-01-23 22:28:57,205:INFO:discord.gateway: Shard ID None has connected to Gateway (Session ID: 74f40bd241f62364be79128c197ac4c4).
2024-01-23 22:29:00,751:INFO:discord: Command: /vouches shauuu_ Divisão 1 by shauuu_
2024-01-23 22:29:01,139:ERROR:discord.app_commands.tree: Ignoring exception in command 'vouches'
Traceback (most recent call last):
  File "D:\PyCharmProjects\Vouch Bot\.venv\lib\site-packages\discord\app_commands\commands.py", line 827, in _do_call
    return await self._callback(self.binding, interaction, **params)  # type: ignore
  File "D:\PyCharmProjects\Vouch Bot\commands.py", line 106, in vouches
    if embed.fields.len() == 0:
AttributeError: 'list' object has no attribute 'len'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\PyCharmProjects\Vouch Bot\.venv\lib\site-packages\discord\app_commands\tree.py", line 1248, in _call
    await command._invoke_with_namespace(interaction, namespace)
  File "D:\PyCharmProjects\Vouch Bot\.venv\lib\site-packages\discord\app_commands\commands.py", line 853, in _invoke_with_namespace
    return await self._do_call(interaction, transformed_values)
  File "D:\PyCharmProjects\Vouch Bot\.venv\lib\site-packages\discord\app_commands\commands.py", line 846, in _do_call
    raise CommandInvokeError(self, e) from e
discord.app_commands.errors.CommandInvokeError: Command 'vouches' raised an exception: AttributeError: 'list' object has no attribute 'len'
2024-01-23 22:31:36,887:WARNING:discord.client: PyNaCl is not installed, voice will NOT be supported
2024-01-23 22:31:36,901:INFO:discord.client: logging in using static token
2024-01-23 22:31:38,194:INFO:discord.gateway: Shard ID None has connected to Gateway (Session ID: 8dded8e17384a1b6362cdfbf3522df54).
2024-01-23 22:31:57,911:INFO:discord: Command: /vouches shauuu_ Divisão 1 by shauuu_
2024-01-23 22:31:57,914:ERROR:discord.app_commands.tree: Ignoring exception in command 'vouches'
Traceback (most recent call last):
  File "D:\PyCharmProjects\Vouch Bot\.venv\lib\site-packages\discord\app_commands\commands.py", line 827, in _do_call
    return await self._callback(self.binding, interaction, **params)  # type: ignore
  File "D:\PyCharmProjects\Vouch Bot\commands.py", line 104, in vouches
    if embed.fields.len() == 0:
AttributeError: 'list' object has no attribute 'len'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\PyCharmProjects\Vouch Bot\.venv\lib\site-packages\discord\app_commands\tree.py", line 1248, in _call
    await command._invoke_with_namespace(interaction, namespace)
  File "D:\PyCharmProjects\Vouch Bot\.venv\lib\site-packages\discord\app_commands\commands.py", line 853, in _invoke_with_namespace
    return await self._do_call(interaction, transformed_values)
  File "D:\PyCharmProjects\Vouch Bot\.venv\lib\site-packages\discord\app_commands\commands.py", line 846, in _do_call
    raise CommandInvokeError(self, e) from e
discord.app_commands.errors.CommandInvokeError: Command 'vouches' raised an exception: AttributeError: 'list' object has no attribute 'len'
2024-01-23 22:32:21,952:WARNING:discord.client: PyNaCl is not installed, voice will NOT be supported
2024-01-23 22:32:21,966:INFO:discord.client: logging in using static token
2024-01-23 22:32:23,084:INFO:discord.gateway: Shard ID None has connected to Gateway (Session ID: 197c7b5a27c48b5bc278730d0b631fb2).
2024-01-23 22:32:26,691:INFO:discord: Command: /vouches shauuu_ Divisão 1 by shauuu_
2024-01-23 22:32:50,501:INFO:discord: Command: /vouches shauuu_ Divisão 3 by shauuu_
2024-01-23 22:32:50,922:ERROR:discord.app_commands.tree: Ignoring exception in command 'vouches'
Traceback (most recent call last):
  File "D:\PyCharmProjects\Vouch Bot\.venv\lib\site-packages\discord\app_commands\commands.py", line 827, in _do_call
    return await self._callback(self.binding, interaction, **params)  # type: ignore
  File "D:\PyCharmProjects\Vouch Bot\commands.py", line 117, in vouches
    await ctx.response.send_message(embed=embed, ephemeral=True)
  File "D:\PyCharmProjects\Vouch Bot\.venv\lib\site-packages\discord\interactions.py", line 774, in send_message
    raise InteractionResponded(self._parent)
discord.errors.InteractionResponded: This interaction has already been responded to before

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\PyCharmProjects\Vouch Bot\.venv\lib\site-packages\discord\app_commands\tree.py", line 1248, in _call
    await command._invoke_with_namespace(interaction, namespace)
  File "D:\PyCharmProjects\Vouch Bot\.venv\lib\site-packages\discord\app_commands\commands.py", line 853, in _invoke_with_namespace
    return await self._do_call(interaction, transformed_values)
  File "D:\PyCharmProjects\Vouch Bot\.venv\lib\site-packages\discord\app_commands\commands.py", line 846, in _do_call
    raise CommandInvokeError(self, e) from e
discord.app_commands.errors.CommandInvokeError: Command 'vouches' raised an exception: InteractionResponded: This interaction has already been responded to before
2024-01-23 22:44:58,416:INFO:discord: Command: /vouches diogotv_ Divisão 3 by diogotv_
2024-01-23 22:45:20,312:INFO:discord: Command: /give_vouch diogotv_ teste by shauuu_
2024-01-23 22:45:39,168:INFO:discord: Command: /promote diogotv_ Divisão 3 by shauuu_
2024-01-23 22:45:39,523:ERROR:discord.app_commands.tree: Ignoring exception in command 'promote'
Traceback (most recent call last):
  File "D:\PyCharmProjects\Vouch Bot\.venv\lib\site-packages\discord\app_commands\commands.py", line 827, in _do_call
    return await self._callback(self.binding, interaction, **params)  # type: ignore
  File "D:\PyCharmProjects\Vouch Bot\commands.py", line 140, in promote
TypeError: convert_name_to_role() takes 1 positional argument but 2 were given

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\PyCharmProjects\Vouch Bot\.venv\lib\site-packages\discord\app_commands\tree.py", line 1248, in _call
    await command._invoke_with_namespace(interaction, namespace)
  File "D:\PyCharmProjects\Vouch Bot\.venv\lib\site-packages\discord\app_commands\commands.py", line 853, in _invoke_with_namespace
    return await self._do_call(interaction, transformed_values)
  File "D:\PyCharmProjects\Vouch Bot\.venv\lib\site-packages\discord\app_commands\commands.py", line 842, in _do_call
    raise CommandInvokeError(self, e) from e
discord.app_commands.errors.CommandInvokeError: Command 'promote' raised an exception: TypeError: convert_name_to_role() takes 1 positional argument but 2 were given
2024-01-23 22:45:55,620:INFO:discord: Command: /give_vouch diogotv_ teste by shauuu_
2024-01-23 22:46:08,017:INFO:discord: Command: /vouches diogotv_ Divisão 2 by shauuu_
2024-01-23 22:46:12,399:INFO:discord: Command: /vouches diogotv_ Divisão 3 by shauuu_
2024-01-23 22:46:12,981:ERROR:discord.app_commands.tree: Ignoring exception in command 'vouches'
Traceback (most recent call last):
  File "D:\PyCharmProjects\Vouch Bot\.venv\lib\site-packages\discord\app_commands\commands.py", line 827, in _do_call
    return await self._callback(self.binding, interaction, **params)  # type: ignore
  File "D:\PyCharmProjects\Vouch Bot\commands.py", line 117, in vouches
  File "D:\PyCharmProjects\Vouch Bot\.venv\lib\site-packages\discord\interactions.py", line 774, in send_message
    raise InteractionResponded(self._parent)
discord.errors.InteractionResponded: This interaction has already been responded to before

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\PyCharmProjects\Vouch Bot\.venv\lib\site-packages\discord\app_commands\tree.py", line 1248, in _call
    await command._invoke_with_namespace(interaction, namespace)
  File "D:\PyCharmProjects\Vouch Bot\.venv\lib\site-packages\discord\app_commands\commands.py", line 853, in _invoke_with_namespace
    return await self._do_call(interaction, transformed_values)
  File "D:\PyCharmProjects\Vouch Bot\.venv\lib\site-packages\discord\app_commands\commands.py", line 846, in _do_call
    raise CommandInvokeError(self, e) from e
discord.app_commands.errors.CommandInvokeError: Command 'vouches' raised an exception: InteractionResponded: This interaction has already been responded to before
2024-01-23 22:46:29,187:INFO:discord: Command: /vouches diogotv_ Divisão 3 by diogotv_
2024-01-23 22:46:29,565:ERROR:discord.app_commands.tree: Ignoring exception in command 'vouches'
Traceback (most recent call last):
  File "D:\PyCharmProjects\Vouch Bot\.venv\lib\site-packages\discord\app_commands\commands.py", line 827, in _do_call
    return await self._callback(self.binding, interaction, **params)  # type: ignore
  File "D:\PyCharmProjects\Vouch Bot\commands.py", line 117, in vouches
  File "D:\PyCharmProjects\Vouch Bot\.venv\lib\site-packages\discord\interactions.py", line 774, in send_message
    raise InteractionResponded(self._parent)
discord.errors.InteractionResponded: This interaction has already been responded to before

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\PyCharmProjects\Vouch Bot\.venv\lib\site-packages\discord\app_commands\tree.py", line 1248, in _call
    await command._invoke_with_namespace(interaction, namespace)
  File "D:\PyCharmProjects\Vouch Bot\.venv\lib\site-packages\discord\app_commands\commands.py", line 853, in _invoke_with_namespace
    return await self._do_call(interaction, transformed_values)
  File "D:\PyCharmProjects\Vouch Bot\.venv\lib\site-packages\discord\app_commands\commands.py", line 846, in _do_call
    raise CommandInvokeError(self, e) from e
discord.app_commands.errors.CommandInvokeError: Command 'vouches' raised an exception: InteractionResponded: This interaction has already been responded to before
2024-01-23 22:49:47,447:WARNING:discord.client: PyNaCl is not installed, voice will NOT be supported
2024-01-23 22:49:47,460:INFO:discord.client: logging in using static token
2024-01-23 22:49:48,604:INFO:discord.gateway: Shard ID None has connected to Gateway (Session ID: 546a1c1dfbe57e1a26898b67f43922f3).
2024-01-23 22:51:22,916:WARNING:discord.client: PyNaCl is not installed, voice will NOT be supported
2024-01-23 22:51:22,930:INFO:discord.client: logging in using static token
2024-01-23 22:51:24,136:INFO:discord.gateway: Shard ID None has connected to Gateway (Session ID: b3414c3ade56f37d49938c1af8676217).
2024-01-23 22:51:40,963:INFO:discord: Command: /vouches diogotv_ Divisão 3 by shauuu_
2024-01-23 22:51:45,679:INFO:discord: Command: /vouches diogotv_ Divisão 3 by diogotv_
2024-01-23 22:52:14,263:INFO:discord: Command: /vouches diogotv_ Divisão 3 by diogotv_
2024-01-23 22:52:20,911:INFO:discord: Command: /vouches diogotv_ Divisão 2 by shauuu_
2024-01-23 22:52:57,987:INFO:discord: Command: /vouches diogotv_ Divisão 3 by shauuu_
2024-01-23 22:53:50,650:WARNING:discord.client: PyNaCl is not installed, voice will NOT be supported
2024-01-23 22:53:50,664:INFO:discord.client: logging in using static token
2024-01-23 22:53:51,771:INFO:discord.gateway: Shard ID None has connected to Gateway (Session ID: c86c2ace9b5a38f732a9850d91d0c1b9).
2024-01-23 22:54:06,441:INFO:discord: Command: /vouches diogotv_ Divisão 2 by diogotv_
2024-01-23 22:54:34,062:WARNING:discord.client: PyNaCl is not installed, voice will NOT be supported
2024-01-23 22:54:34,078:INFO:discord.client: logging in using static token
2024-01-23 22:54:35,189:INFO:discord.gateway: Shard ID None has connected to Gateway (Session ID: f161fe2abb2cab9af90f52538f3ef2a8).
2024-01-23 22:54:56,369:INFO:discord: Command: /vouches diogotv_ Divisão 2 by diogotv_
2024-01-23 22:55:03,396:INFO:discord: Command: /vouches diogotv_ Divisão 1 by diogotv_
2024-01-23 22:55:27,867:INFO:discord: Command: /promote shauuu_ Divisão 1 by shauuu_
2024-01-23 22:57:19,370:WARNING:discord.client: PyNaCl is not installed, voice will NOT be supported
2024-01-23 22:57:19,383:INFO:discord.client: logging in using static token
2024-01-23 22:57:20,491:INFO:discord.gateway: Shard ID None has connected to Gateway (Session ID: 908b7a890316449aabf66fe14e5b9d35).
2024-01-23 22:57:25,081:INFO:discord: Command: /promote shauuu_ Divisão 1 by shauuu_
2024-01-24 01:22:37,221:WARNING:discord.client: PyNaCl is not installed, voice will NOT be supported
2024-01-24 01:22:37,314:INFO:discord.client: logging in using static token
2024-01-24 01:22:38,539:INFO:discord.gateway: Shard ID None has connected to Gateway (Session ID: 4e8b8702029980e997d8567e0989b1a9).
2024-01-24 20:06:12,103:WARNING:discord.client: PyNaCl is not installed, voice will NOT be supported
2024-01-24 20:06:40,533:WARNING:discord.client: PyNaCl is not installed, voice will NOT be supported
2024-01-24 20:06:40,546:INFO:discord.client: logging in using static token
2024-01-24 20:06:41,798:INFO:discord.gateway: Shard ID None has connected to Gateway (Session ID: 5c58342684090d493ce84280a103aa8e).
2024-01-24 20:07:01,579:INFO:discord: Command: /disponivel Choice(name='4v4', value=4) by shauuu_
2024-01-24 20:07:10,918:INFO:discord: Command: /disponivel Choice(name='1v1', value=1) by shauuu_
2024-01-24 20:07:42,782:WARNING:discord.client: PyNaCl is not installed, voice will NOT be supported
2024-01-24 20:07:42,796:INFO:discord.client: logging in using static token
2024-01-24 20:07:43,891:INFO:discord.gateway: Shard ID None has connected to Gateway (Session ID: cb35f29d3d24603b8c06aec0fba70a88).
2024-01-24 20:07:50,794:INFO:discord: Command: /disponivel Choice(name='1v1', value=1) by shauuu_
2024-01-24 20:16:29,703:WARNING:discord.client: PyNaCl is not installed, voice will NOT be supported
2024-01-24 20:16:29,725:INFO:discord.client: logging in using static token
2024-01-24 20:16:30,944:INFO:discord.gateway: Shard ID None has connected to Gateway (Session ID: f84ac318da6a4b5a38698240c42836aa).
2024-01-24 20:16:49,571:INFO:discord: Command: /disponivel Choice(name='1v1', value=1) by shauuu_
2024-01-24 20:17:13,619:WARNING:discord.client: PyNaCl is not installed, voice will NOT be supported
2024-01-24 20:17:13,632:INFO:discord.client: logging in using static token
2024-01-24 20:17:14,965:INFO:discord.gateway: Shard ID None has connected to Gateway (Session ID: 868cb5ab110f98c6224abf4969fb095e).
2024-01-24 20:17:23,852:INFO:discord: Command: /disponivel Choice(name='1v1', value=1) by shauuu_
2024-01-24 20:17:35,007:WARNING:discord.client: PyNaCl is not installed, voice will NOT be supported
2024-01-24 20:17:35,020:INFO:discord.client: logging in using static token
2024-01-24 20:17:36,257:INFO:discord.gateway: Shard ID None has connected to Gateway (Session ID: c264ac1e5c732785b52a702f7f0becb9).
2024-01-24 20:17:46,653:INFO:discord: Command: /disponivel Choice(name='1v1', value=1) by shauuu_
2024-01-24 20:23:30,042:WARNING:discord.client: PyNaCl is not installed, voice will NOT be supported
2024-01-24 20:23:30,076:INFO:discord.client: logging in using static token
2024-01-24 20:23:31,154:INFO:discord.gateway: Shard ID None has connected to Gateway (Session ID: 6c26406026f4a771b8eba4de30a86d4f).
2024-01-24 20:24:07,520:INFO:discord: Command: /disponivel Choice(name='1v1', value=1) by shauuu_
2024-01-24 20:24:22,642:WARNING:discord.client: PyNaCl is not installed, voice will NOT be supported
2024-01-24 20:24:22,655:INFO:discord.client: logging in using static token
2024-01-24 20:24:23,762:INFO:discord.gateway: Shard ID None has connected to Gateway (Session ID: ccbd8ce78ac3a67c727613c32d9ccb37).
2024-01-24 20:24:29,318:INFO:discord: Command: /disponivel Choice(name='1v1', value=1) by shauuu_
2024-01-24 20:24:41,249:WARNING:discord.client: PyNaCl is not installed, voice will NOT be supported
2024-01-24 20:24:41,262:INFO:discord.client: logging in using static token
2024-01-24 20:24:42,764:INFO:discord.gateway: Shard ID None has connected to Gateway (Session ID: 483765a819285ee94c8f415081ed615d).
2024-01-24 20:24:46,722:INFO:discord: Command: /disponivel Choice(name='1v1', value=1) by shauuu_
2024-01-24 20:24:55,880:WARNING:discord.client: PyNaCl is not installed, voice will NOT be supported
2024-01-24 20:24:55,895:INFO:discord.client: logging in using static token
2024-01-24 20:24:57,018:INFO:discord.gateway: Shard ID None has connected to Gateway (Session ID: 5747e05aa0afeda0605e0108ea505e0f).
2024-01-24 20:25:01,546:INFO:discord: Command: /disponivel Choice(name='1v1', value=1) by shauuu_
2024-01-24 20:25:13,746:WARNING:discord.client: PyNaCl is not installed, voice will NOT be supported
2024-01-24 20:25:13,760:INFO:discord.client: logging in using static token
2024-01-24 20:25:15,036:INFO:discord.gateway: Shard ID None has connected to Gateway (Session ID: 4942ce943dd2aac8923c2eca99ec1d4a).
2024-01-24 20:25:17,334:WARNING:discord.http: We are being rate limited. PUT https://discord.com/api/v10/applications/1198496806124933190/commands responded with 429. Retrying in 8.77 seconds.
2024-01-24 20:25:25,976:INFO:discord: Command: /disponivel Choice(name='1v1', value=1) by shauuu_
2024-01-24 20:25:55,532:WARNING:discord.client: PyNaCl is not installed, voice will NOT be supported
2024-01-24 20:25:55,546:INFO:discord.client: logging in using static token
2024-01-24 20:25:56,819:INFO:discord.gateway: Shard ID None has connected to Gateway (Session ID: aa3f1b15307ad749ff7b241a4bac4c23).
2024-01-24 20:26:06,727:INFO:discord: Command: /disponivel Choice(name='1v1', value=1) by shauuu_
2024-01-24 20:26:52,906:WARNING:discord.client: PyNaCl is not installed, voice will NOT be supported
2024-01-24 20:26:52,921:INFO:discord.client: logging in using static token
2024-01-24 20:26:54,023:INFO:discord.gateway: Shard ID None has connected to Gateway (Session ID: 04392c30c02bf861df77966e1fd43f71).
2024-01-24 20:26:58,658:INFO:discord: Command: /disponivel Choice(name='1v1', value=1) by shauuu_
2024-01-24 20:27:29,694:WARNING:discord.client: PyNaCl is not installed, voice will NOT be supported
2024-01-24 20:27:29,707:INFO:discord.client: logging in using static token
2024-01-24 20:27:30,885:INFO:discord.gateway: Shard ID None has connected to Gateway (Session ID: 7adb9b334574f6c26bfbc6a704342bee).
2024-01-24 20:27:39,851:INFO:discord: Command: /disponivel Choice(name='1v1', value=1) by shauuu_
2024-01-24 20:27:51,383:INFO:discord: Command: /disponivel Choice(name='1v1', value=1) by shauuu_
2024-01-24 20:29:42,065:INFO:discord: Command: /promote shauuu_ Divisão 1 by shauuu_
2024-01-24 20:29:42,170:ERROR:discord.app_commands.tree: Ignoring exception in command 'promote'
Traceback (most recent call last):
  File "D:\PyCharmProjects\Vouch Bot\.venv\lib\site-packages\discord\app_commands\commands.py", line 827, in _do_call
    return await self._callback(self.binding, interaction, **params)  # type: ignore
  File "D:\PyCharmProjects\Vouch Bot\commands.py", line 148, in promote
    if not await check_permission(ctx):
TypeError: object bool can't be used in 'await' expression

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\PyCharmProjects\Vouch Bot\.venv\lib\site-packages\discord\app_commands\tree.py", line 1248, in _call
    await command._invoke_with_namespace(interaction, namespace)
  File "D:\PyCharmProjects\Vouch Bot\.venv\lib\site-packages\discord\app_commands\commands.py", line 853, in _invoke_with_namespace
    return await self._do_call(interaction, transformed_values)
  File "D:\PyCharmProjects\Vouch Bot\.venv\lib\site-packages\discord\app_commands\commands.py", line 842, in _do_call
    raise CommandInvokeError(self, e) from e
discord.app_commands.errors.CommandInvokeError: Command 'promote' raised an exception: TypeError: object bool can't be used in 'await' expression
2024-01-24 20:32:53,919:WARNING:discord.client: PyNaCl is not installed, voice will NOT be supported
2024-01-24 20:32:53,934:INFO:discord.client: logging in using static token
2024-01-24 20:32:55,214:INFO:discord.gateway: Shard ID None has connected to Gateway (Session ID: 8a6f9a4f617ca3978195f322f9cc89e6).
2024-01-24 20:33:05,834:INFO:discord: Command: /promote shauuu_ Divisão 1 by shauuu_
2024-01-24 20:43:15,520:WARNING:discord.client: PyNaCl is not installed, voice will NOT be supported
2024-01-24 20:43:15,538:INFO:discord.client: logging in using static token
2024-01-24 20:43:16,655:INFO:discord.gateway: Shard ID None has connected to Gateway (Session ID: 270202e7a751dbf905dbeb239528e1e3).
2024-01-24 20:43:28,145:INFO:discord: Command: /promote shauuu_ Divisão 2 by shauuu_
2024-01-24 20:43:35,374:INFO:discord: Command: /promote shauuu_ Divisão 2 by shauuu_
2024-01-24 20:43:36,050:ERROR:discord.app_commands.tree: Ignoring exception in command 'promote'
Traceback (most recent call last):
  File "D:\PyCharmProjects\Vouch Bot\.venv\lib\site-packages\discord\app_commands\commands.py", line 827, in _do_call
    return await self._callback(self.binding, interaction, **params)  # type: ignore
  File "D:\PyCharmProjects\Vouch Bot\commands.py", line 183, in promote
    await member.remove_roles(member_role)
  File "D:\PyCharmProjects\Vouch Bot\.venv\lib\site-packages\discord\member.py", line 1096, in remove_roles
    await req(guild_id, user_id, role.id, reason=reason)
  File "D:\PyCharmProjects\Vouch Bot\.venv\lib\site-packages\discord\http.py", line 739, in request
    raise Forbidden(response, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50013): Missing Permissions

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\PyCharmProjects\Vouch Bot\.venv\lib\site-packages\discord\app_commands\tree.py", line 1248, in _call
    await command._invoke_with_namespace(interaction, namespace)
  File "D:\PyCharmProjects\Vouch Bot\.venv\lib\site-packages\discord\app_commands\commands.py", line 853, in _invoke_with_namespace
    return await self._do_call(interaction, transformed_values)
  File "D:\PyCharmProjects\Vouch Bot\.venv\lib\site-packages\discord\app_commands\commands.py", line 846, in _do_call
    raise CommandInvokeError(self, e) from e
discord.app_commands.errors.CommandInvokeError: Command 'promote' raised an exception: Forbidden: 403 Forbidden (error code: 50013): Missing Permissions
2024-01-24 20:43:50,919:INFO:discord: Command: /promote shauuu_ Divisão 3 by shauuu_
2024-01-24 20:43:51,419:ERROR:discord.app_commands.tree: Ignoring exception in command 'promote'
Traceback (most recent call last):
  File "D:\PyCharmProjects\Vouch Bot\.venv\lib\site-packages\discord\app_commands\commands.py", line 827, in _do_call
    return await self._callback(self.binding, interaction, **params)  # type: ignore
  File "D:\PyCharmProjects\Vouch Bot\commands.py", line 183, in promote
    await member.remove_roles(member_role)
  File "D:\PyCharmProjects\Vouch Bot\.venv\lib\site-packages\discord\member.py", line 1096, in remove_roles
    await req(guild_id, user_id, role.id, reason=reason)
  File "D:\PyCharmProjects\Vouch Bot\.venv\lib\site-packages\discord\http.py", line 739, in request
    raise Forbidden(response, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50013): Missing Permissions

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\PyCharmProjects\Vouch Bot\.venv\lib\site-packages\discord\app_commands\tree.py", line 1248, in _call
    await command._invoke_with_namespace(interaction, namespace)
  File "D:\PyCharmProjects\Vouch Bot\.venv\lib\site-packages\discord\app_commands\commands.py", line 853, in _invoke_with_namespace
    return await self._do_call(interaction, transformed_values)
  File "D:\PyCharmProjects\Vouch Bot\.venv\lib\site-packages\discord\app_commands\commands.py", line 846, in _do_call
    raise CommandInvokeError(self, e) from e
discord.app_commands.errors.CommandInvokeError: Command 'promote' raised an exception: Forbidden: 403 Forbidden (error code: 50013): Missing Permissions
2024-01-24 20:44:00,894:INFO:discord: Command: /promote shauuu_ Divisão 3 by shauuu_
2024-01-24 20:44:01,364:ERROR:discord.app_commands.tree: Ignoring exception in command 'promote'
Traceback (most recent call last):
  File "D:\PyCharmProjects\Vouch Bot\.venv\lib\site-packages\discord\app_commands\commands.py", line 827, in _do_call
    return await self._callback(self.binding, interaction, **params)  # type: ignore
  File "D:\PyCharmProjects\Vouch Bot\commands.py", line 183, in promote
    await member.remove_roles(member_role)
  File "D:\PyCharmProjects\Vouch Bot\.venv\lib\site-packages\discord\member.py", line 1096, in remove_roles
    await req(guild_id, user_id, role.id, reason=reason)
  File "D:\PyCharmProjects\Vouch Bot\.venv\lib\site-packages\discord\http.py", line 739, in request
    raise Forbidden(response, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50013): Missing Permissions

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\PyCharmProjects\Vouch Bot\.venv\lib\site-packages\discord\app_commands\tree.py", line 1248, in _call
    await command._invoke_with_namespace(interaction, namespace)
  File "D:\PyCharmProjects\Vouch Bot\.venv\lib\site-packages\discord\app_commands\commands.py", line 853, in _invoke_with_namespace
    return await self._do_call(interaction, transformed_values)
  File "D:\PyCharmProjects\Vouch Bot\.venv\lib\site-packages\discord\app_commands\commands.py", line 846, in _do_call
    raise CommandInvokeError(self, e) from e
discord.app_commands.errors.CommandInvokeError: Command 'promote' raised an exception: Forbidden: 403 Forbidden (error code: 50013): Missing Permissions
2024-01-24 20:44:39,419:INFO:discord: Command: /promote shauuu_ Divisão 2 by shauuu_
2024-01-24 20:44:51,832:INFO:discord: Command: /promote shauuu_ Divisão 1 by shauuu_
2024-01-24 20:44:57,832:INFO:discord: Command: /promote shauuu_ Divisão 1 by shauuu_
2024-01-24 20:45:32,329:WARNING:discord.client: PyNaCl is not installed, voice will NOT be supported
2024-01-24 20:45:32,345:INFO:discord.client: logging in using static token
2024-01-24 20:45:33,664:INFO:discord.gateway: Shard ID None has connected to Gateway (Session ID: cd8b6f6187d37c9a43e6bb6c48dd1df2).
2024-01-24 20:45:41,804:INFO:discord: Command: /promote shauuu_ Divisão 1 by shauuu_
2024-01-24 20:45:48,439:INFO:discord: Command: /promote shauuu_ Divisão 2 by shauuu_
2024-01-24 20:49:35,187:INFO:discord: Command: /promote shauuu_ Divisão 2 by shauuu_
2024-01-24 20:49:47,710:WARNING:discord.client: PyNaCl is not installed, voice will NOT be supported
2024-01-24 20:49:47,739:INFO:discord.client: logging in using static token
2024-01-24 20:49:49,074:INFO:discord.gateway: Shard ID None has connected to Gateway (Session ID: cd4fce9d274fa718a5688869c29cb8fb).
2024-01-24 20:49:53,683:INFO:discord: Command: /promote shauuu_ Divisão 2 by shauuu_
2024-01-24 21:01:35,525:WARNING:discord.client: PyNaCl is not installed, voice will NOT be supported
2024-01-24 21:01:35,566:INFO:discord.client: logging in using static token
2024-01-24 21:01:36,828:INFO:discord.gateway: Shard ID None has connected to Gateway (Session ID: 02808a4ac624614a2daaaa09b494fa88).
2024-01-24 21:01:49,612:INFO:discord: Command: /promote shauuu_ Casual by shauuu_
2024-01-24 21:02:22,626:INFO:discord: Command: /vouches shauuu_ Divisão 3 by shauuu_
2024-01-24 21:02:29,364:INFO:discord: Command: /vouches shauuu_ Casual by shauuu_
2024-01-24 21:02:32,920:INFO:discord: Command: /vouches shauuu_ Divisão 1 by shauuu_
2024-01-24 21:05:27,381:INFO:discord: Command: /give_vouch shauuu_ teste by shauuu_
2024-01-24 21:07:20,023:WARNING:discord.client: PyNaCl is not installed, voice will NOT be supported
2024-01-24 21:07:20,042:INFO:discord.client: logging in using static token
2024-01-24 21:07:21,170:INFO:discord.gateway: Shard ID None has connected to Gateway (Session ID: 50968028006af53b6905109add57fcf2).
2024-01-24 21:07:26,591:INFO:discord: Command: /give_vouch shauuu_ teste by shauuu_
2024-01-24 21:07:36,426:INFO:discord: Command: /vouches shauuu_ Divisão 3 by shauuu_
2024-01-24 21:07:36,429:ERROR:discord.app_commands.tree: Ignoring exception in command 'vouches'
Traceback (most recent call last):
  File "D:\PyCharmProjects\Vouch Bot\.venv\lib\site-packages\discord\app_commands\commands.py", line 827, in _do_call
    return await self._callback(self.binding, interaction, **params)  # type: ignore
  File "D:\PyCharmProjects\Vouch Bot\commands.py", line 117, in vouches
    Vouch.get_division_at_the_insertion(usuario.id, vouch_id).split(" ")[1]):
IndexError: list index out of range

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\PyCharmProjects\Vouch Bot\.venv\lib\site-packages\discord\app_commands\tree.py", line 1248, in _call
    await command._invoke_with_namespace(interaction, namespace)
  File "D:\PyCharmProjects\Vouch Bot\.venv\lib\site-packages\discord\app_commands\commands.py", line 853, in _invoke_with_namespace
    return await self._do_call(interaction, transformed_values)
  File "D:\PyCharmProjects\Vouch Bot\.venv\lib\site-packages\discord\app_commands\commands.py", line 846, in _do_call
    raise CommandInvokeError(self, e) from e
discord.app_commands.errors.CommandInvokeError: Command 'vouches' raised an exception: IndexError: list index out of range
2024-01-24 21:09:10,671:WARNING:discord.client: PyNaCl is not installed, voice will NOT be supported
2024-01-24 21:09:10,689:INFO:discord.client: logging in using static token
2024-01-24 21:09:12,129:INFO:discord.gateway: Shard ID None has connected to Gateway (Session ID: b5b5c822dddcabeee213da0d2b41f7f7).
2024-01-24 21:09:15,895:INFO:discord: Command: /vouches shauuu_ Divisão 3 by shauuu_
2024-01-24 21:09:15,898:ERROR:discord.app_commands.tree: Ignoring exception in command 'vouches'
Traceback (most recent call last):
  File "D:\PyCharmProjects\Vouch Bot\.venv\lib\site-packages\discord\app_commands\commands.py", line 827, in _do_call
    return await self._callback(self.binding, interaction, **params)  # type: ignore
  File "D:\PyCharmProjects\Vouch Bot\commands.py", line 118, in vouches
    Vouch.get_division_at_the_insertion(usuario.id, vouch_id).split(" ")[1]):
IndexError: list index out of range

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\PyCharmProjects\Vouch Bot\.venv\lib\site-packages\discord\app_commands\tree.py", line 1248, in _call
    await command._invoke_with_namespace(interaction, namespace)
  File "D:\PyCharmProjects\Vouch Bot\.venv\lib\site-packages\discord\app_commands\commands.py", line 853, in _invoke_with_namespace
    return await self._do_call(interaction, transformed_values)
  File "D:\PyCharmProjects\Vouch Bot\.venv\lib\site-packages\discord\app_commands\commands.py", line 846, in _do_call
    raise CommandInvokeError(self, e) from e
discord.app_commands.errors.CommandInvokeError: Command 'vouches' raised an exception: IndexError: list index out of range
2024-01-24 21:12:10,730:WARNING:discord.client: PyNaCl is not installed, voice will NOT be supported
2024-01-24 21:12:10,744:INFO:discord.client: logging in using static token
2024-01-24 21:12:11,960:INFO:discord.gateway: Shard ID None has connected to Gateway (Session ID: 60b628ea49a0ac34729418da0beb85bd).
2024-01-24 21:12:34,881:WARNING:discord.client: PyNaCl is not installed, voice will NOT be supported
2024-01-24 21:12:34,896:INFO:discord.client: logging in using static token
2024-01-24 21:12:35,967:INFO:discord.gateway: Shard ID None has connected to Gateway (Session ID: fb536430acbc0101fa8af4f88e54c281).
2024-01-24 21:12:46,441:INFO:discord: Command: /vouches shauuu_ Divisão 3 by shauuu_
2024-01-24 21:12:52,783:INFO:discord: Command: /vouches shauuu_ Casual by shauuu_
2024-01-24 21:17:17,694:WARNING:discord.client: PyNaCl is not installed, voice will NOT be supported
2024-01-24 21:17:17,708:INFO:discord.client: logging in using static token
2024-01-24 21:17:18,885:INFO:discord.gateway: Shard ID None has connected to Gateway (Session ID: 893c04843fa1719fac7b2e37e2e26ab4).
2024-01-24 21:17:41,411:INFO:discord: Command: /promote shauuu_ Divisão 2 by shauuu_
2024-01-24 21:18:54,950:WARNING:discord.client: PyNaCl is not installed, voice will NOT be supported
2024-01-24 21:18:54,965:INFO:discord.client: logging in using static token
2024-01-24 21:18:56,110:INFO:discord.gateway: Shard ID None has connected to Gateway (Session ID: 3246c608b1778b26b311e0dd87e65610).
2024-01-24 21:19:03,137:INFO:discord: Command: /promote shauuu_ Divisão 1 by shauuu_
2024-01-24 21:19:06,463:ERROR:discord.app_commands.tree: Ignoring exception in command 'promote'
Traceback (most recent call last):
  File "D:\PyCharmProjects\Vouch Bot\.venv\lib\site-packages\discord\app_commands\commands.py", line 827, in _do_call
    return await self._callback(self.binding, interaction, **params)  # type: ignore
  File "D:\PyCharmProjects\Vouch Bot\commands.py", line 199, in promote
    await ctx.response.send_message(embed=embed, ephemeral=True)
  File "D:\PyCharmProjects\Vouch Bot\.venv\lib\site-packages\discord\interactions.py", line 801, in send_message
    await adapter.create_interaction_response(
  File "D:\PyCharmProjects\Vouch Bot\.venv\lib\site-packages\discord\webhook\async_.py", line 219, in request
    raise NotFound(response, data)
discord.errors.NotFound: 404 Not Found (error code: 10062): Unknown interaction

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\PyCharmProjects\Vouch Bot\.venv\lib\site-packages\discord\app_commands\tree.py", line 1248, in _call
    await command._invoke_with_namespace(interaction, namespace)
  File "D:\PyCharmProjects\Vouch Bot\.venv\lib\site-packages\discord\app_commands\commands.py", line 853, in _invoke_with_namespace
    return await self._do_call(interaction, transformed_values)
  File "D:\PyCharmProjects\Vouch Bot\.venv\lib\site-packages\discord\app_commands\commands.py", line 846, in _do_call
    raise CommandInvokeError(self, e) from e
discord.app_commands.errors.CommandInvokeError: Command 'promote' raised an exception: NotFound: 404 Not Found (error code: 10062): Unknown interaction
2024-01-24 21:20:56,921:WARNING:discord.client: PyNaCl is not installed, voice will NOT be supported
2024-01-24 21:20:56,935:INFO:discord.client: logging in using static token
2024-01-24 21:20:58,050:INFO:discord.gateway: Shard ID None has connected to Gateway (Session ID: 0f512e4c0fe18d15ab4d5a727320c7a1).
2024-01-24 21:21:10,477:INFO:discord: Command: /promote shauuu_ Divisão 2 by shauuu_
2024-01-24 21:21:34,774:WARNING:discord.client: PyNaCl is not installed, voice will NOT be supported
2024-01-24 21:21:34,788:INFO:discord.client: logging in using static token
2024-01-24 21:21:36,046:INFO:discord.gateway: Shard ID None has connected to Gateway (Session ID: bd71dc82c949333b4f5970d5d25c7f5f).
2024-01-24 21:21:43,385:INFO:discord: Command: /promote shauuu_ Divisão 1 by shauuu_
2024-01-24 21:24:49,939:INFO:discord: Command: /promote shauuu_ Casual by shauuu_
2024-01-24 21:25:39,738:WARNING:discord.client: PyNaCl is not installed, voice will NOT be supported
2024-01-24 21:25:39,789:INFO:discord.client: logging in using static token
2024-01-24 21:25:41,020:INFO:discord.gateway: Shard ID None has connected to Gateway (Session ID: ad9b43fa0fdc282a830bb8ec0af26fa8).
2024-01-24 21:25:49,087:INFO:discord: Command: /promote shauuu_ Casual by shauuu_
2024-01-24 21:25:54,180:INFO:discord: Command: /promote shauuu_ Divisão 1 by shauuu_
2024-01-24 21:30:42,842:WARNING:discord.client: PyNaCl is not installed, voice will NOT be supported
2024-01-24 21:30:42,863:INFO:discord.client: logging in using static token
2024-01-24 21:30:44,230:INFO:discord.gateway: Shard ID None has connected to Gateway (Session ID: 69d77ee3f3ca9fdff6e68967f474e986).
2024-01-24 23:05:16,624:WARNING:discord.client: PyNaCl is not installed, voice will NOT be supported
2024-01-24 23:05:16,719:INFO:discord.client: logging in using static token
2024-01-24 23:05:17,938:INFO:discord.gateway: Shard ID None has connected to Gateway (Session ID: 579d99583cad32506ad12a07b1240a63).
2024-01-24 23:06:04,672:INFO:discord: Command: /vouches shauuu_ Divisão 1 by shauuu_
2024-01-24 23:07:03,917:INFO:discord: Command: /give_vouch shauuu_ teste by shauuu_
2024-01-24 23:07:13,636:INFO:discord: Command: /vouches shauuu_ Divisão 1 by shauuu_
2024-01-24 23:52:39,746:INFO:discord.gateway: Shard ID None has successfully RESUMED session 579d99583cad32506ad12a07b1240a63.
2024-01-25 00:20:19,579:INFO:discord: Command: /vouches shauuu_ Divisão 2 by shauuu_
2024-01-25 00:20:56,122:INFO:discord: Command: /give_vouch shauuu_ ser ruim by shauuu_
2024-01-25 00:21:08,456:INFO:discord: Command: /vouches shauuu_ Divisão 2 by shauuu_
2024-01-25 00:22:20,465:INFO:discord: Command: /vouches shauuu_ Divisão 3 by shauuu_
2024-01-25 00:28:37,906:WARNING:discord.client: PyNaCl is not installed, voice will NOT be supported
2024-01-25 00:28:37,923:INFO:discord.client: logging in using static token
2024-01-25 00:28:39,055:INFO:discord.gateway: Shard ID None has connected to Gateway (Session ID: d3489a2de38baa8ae0936417910fd0cc).
2024-01-25 00:28:49,393:INFO:discord: Command: /vouches shauuu_ Divisão 3 by shauuu_
2024-01-25 00:28:49,393:ERROR:discord.app_commands.tree: Ignoring exception in command 'vouches'
Traceback (most recent call last):
  File "D:\PyCharmProjects\Vouch Bot\.venv\lib\site-packages\discord\app_commands\commands.py", line 827, in _do_call
    return await self._callback(self.binding, interaction, **params)  # type: ignore
  File "D:\PyCharmProjects\Vouch Bot\commands.py", line 116, in vouches
    if current_division and current_division != "Casual" and int(current_division.split(" ")[1]) < int(rank.split(" ")[1]):
AttributeError: 'Choice' object has no attribute 'split'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\PyCharmProjects\Vouch Bot\.venv\lib\site-packages\discord\app_commands\tree.py", line 1248, in _call
    await command._invoke_with_namespace(interaction, namespace)
  File "D:\PyCharmProjects\Vouch Bot\.venv\lib\site-packages\discord\app_commands\commands.py", line 853, in _invoke_with_namespace
    return await self._do_call(interaction, transformed_values)
  File "D:\PyCharmProjects\Vouch Bot\.venv\lib\site-packages\discord\app_commands\commands.py", line 846, in _do_call
    raise CommandInvokeError(self, e) from e
discord.app_commands.errors.CommandInvokeError: Command 'vouches' raised an exception: AttributeError: 'Choice' object has no attribute 'split'
2024-01-25 00:29:06,639:WARNING:discord.client: PyNaCl is not installed, voice will NOT be supported
2024-01-25 00:29:06,653:INFO:discord.client: logging in using static token
2024-01-25 00:29:07,750:INFO:discord.gateway: Shard ID None has connected to Gateway (Session ID: 222c476d5c36acfb269ecea1ab7bde49).
2024-01-25 00:29:11,837:INFO:discord: Command: /vouches shauuu_ Divisão 3 by shauuu_
2024-01-25 00:29:11,837:ERROR:discord.app_commands.tree: Ignoring exception in command 'vouches'
Traceback (most recent call last):
  File "D:\PyCharmProjects\Vouch Bot\.venv\lib\site-packages\discord\app_commands\commands.py", line 827, in _do_call
    return await self._callback(self.binding, interaction, **params)  # type: ignore
  File "D:\PyCharmProjects\Vouch Bot\commands.py", line 116, in vouches
    if current_division and current_division != "Casual" and int(current_division.split(" ")[1]) < int(rank.split(" ")[1]):
AttributeError: 'Choice' object has no attribute 'split'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\PyCharmProjects\Vouch Bot\.venv\lib\site-packages\discord\app_commands\tree.py", line 1248, in _call
    await command._invoke_with_namespace(interaction, namespace)
  File "D:\PyCharmProjects\Vouch Bot\.venv\lib\site-packages\discord\app_commands\commands.py", line 853, in _invoke_with_namespace
    return await self._do_call(interaction, transformed_values)
  File "D:\PyCharmProjects\Vouch Bot\.venv\lib\site-packages\discord\app_commands\commands.py", line 846, in _do_call
    raise CommandInvokeError(self, e) from e
discord.app_commands.errors.CommandInvokeError: Command 'vouches' raised an exception: AttributeError: 'Choice' object has no attribute 'split'
2024-01-25 00:29:23,061:WARNING:discord.client: PyNaCl is not installed, voice will NOT be supported
2024-01-25 00:29:23,080:INFO:discord.client: logging in using static token
2024-01-25 00:29:24,179:INFO:discord.gateway: Shard ID None has connected to Gateway (Session ID: 69e4e16c5cb7c5fd9e04159058ae0f03).
2024-01-25 00:29:29,869:INFO:discord: Command: /vouches shauuu_ Divisão 3 by shauuu_
2024-01-25 00:29:29,869:ERROR:discord.app_commands.tree: Ignoring exception in command 'vouches'
Traceback (most recent call last):
  File "D:\PyCharmProjects\Vouch Bot\.venv\lib\site-packages\discord\app_commands\commands.py", line 827, in _do_call
    return await self._callback(self.binding, interaction, **params)  # type: ignore
  File "D:\PyCharmProjects\Vouch Bot\commands.py", line 117, in vouches
    if current_division and current_division != "Casual" and int(current_division.split(" ")[1]) < int(rank.split(" ")[1]):
AttributeError: 'Choice' object has no attribute 'split'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\PyCharmProjects\Vouch Bot\.venv\lib\site-packages\discord\app_commands\tree.py", line 1248, in _call
    await command._invoke_with_namespace(interaction, namespace)
  File "D:\PyCharmProjects\Vouch Bot\.venv\lib\site-packages\discord\app_commands\commands.py", line 853, in _invoke_with_namespace
    return await self._do_call(interaction, transformed_values)
  File "D:\PyCharmProjects\Vouch Bot\.venv\lib\site-packages\discord\app_commands\commands.py", line 846, in _do_call
    raise CommandInvokeError(self, e) from e
discord.app_commands.errors.CommandInvokeError: Command 'vouches' raised an exception: AttributeError: 'Choice' object has no attribute 'split'
2024-01-25 00:29:39,965:WARNING:discord.client: PyNaCl is not installed, voice will NOT be supported
2024-01-25 00:29:39,979:INFO:discord.client: logging in using static token
2024-01-25 00:29:41,020:INFO:discord.gateway: Shard ID None has connected to Gateway (Session ID: edba1047e10a5a8608ed3c69f19af988).
2024-01-25 00:29:50,537:INFO:discord: Command: /vouches shauuu_ Divisão 3 by shauuu_
2024-01-25 00:29:50,538:ERROR:discord.app_commands.tree: Ignoring exception in command 'vouches'
Traceback (most recent call last):
  File "D:\PyCharmProjects\Vouch Bot\.venv\lib\site-packages\discord\app_commands\commands.py", line 827, in _do_call
    return await self._callback(self.binding, interaction, **params)  # type: ignore
  File "D:\PyCharmProjects\Vouch Bot\commands.py", line 117, in vouches
    if current_division and current_division != "Casual" and int(current_division.split(" ")[1]) < int(rank.split(" ")[1]):
AttributeError: 'Choice' object has no attribute 'split'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\PyCharmProjects\Vouch Bot\.venv\lib\site-packages\discord\app_commands\tree.py", line 1248, in _call
    await command._invoke_with_namespace(interaction, namespace)
  File "D:\PyCharmProjects\Vouch Bot\.venv\lib\site-packages\discord\app_commands\commands.py", line 853, in _invoke_with_namespace
    return await self._do_call(interaction, transformed_values)
  File "D:\PyCharmProjects\Vouch Bot\.venv\lib\site-packages\discord\app_commands\commands.py", line 846, in _do_call
    raise CommandInvokeError(self, e) from e
discord.app_commands.errors.CommandInvokeError: Command 'vouches' raised an exception: AttributeError: 'Choice' object has no attribute 'split'
2024-01-25 00:30:11,976:WARNING:discord.client: PyNaCl is not installed, voice will NOT be supported
2024-01-25 00:30:11,990:INFO:discord.client: logging in using static token
2024-01-25 00:30:13,049:INFO:discord.gateway: Shard ID None has connected to Gateway (Session ID: afaadc761231d53921114383b5e5d2c9).
2024-01-25 00:30:20,063:INFO:discord: Command: /vouches shauuu_ Divisão 3 by shauuu_
2024-01-25 00:30:49,631:WARNING:discord.client: PyNaCl is not installed, voice will NOT be supported
2024-01-25 00:30:49,656:INFO:discord.client: logging in using static token
2024-01-25 00:30:50,979:INFO:discord.gateway: Shard ID None has connected to Gateway (Session ID: d34766fa88cea8992bcf01384c503153).
2024-01-25 00:30:55,663:INFO:discord: Command: /vouches shauuu_ Divisão 3 by shauuu_
2024-01-25 00:31:36,532:WARNING:discord.client: PyNaCl is not installed, voice will NOT be supported
2024-01-25 00:31:36,546:INFO:discord.client: logging in using static token
2024-01-25 00:31:37,751:INFO:discord.gateway: Shard ID None has connected to Gateway (Session ID: 247a5e0a133429cb11b4e6e0a2725526).
2024-01-25 00:31:48,784:INFO:discord: Command: /vouches shauuu_ Divisão 3 by shauuu_
2024-01-25 00:31:52,396:INFO:discord: Command: /vouches shauuu_ Divisão 2 by shauuu_
2024-01-25 00:31:55,431:INFO:discord: Command: /vouches shauuu_ Divisão 1 by shauuu_
2024-01-25 00:32:22,541:INFO:discord: Command: /vouches shauuu_ Divisão 3 by shauuu_
2024-01-25 00:32:26,373:INFO:discord: Command: /vouches shauuu_ Divisão 2 by shauuu_
2024-01-25 00:32:33,557:WARNING:discord.client: PyNaCl is not installed, voice will NOT be supported
2024-01-25 00:32:33,564:INFO:discord.client: logging in using static token
2024-01-25 00:32:34,628:INFO:discord.gateway: Shard ID None has connected to Gateway (Session ID: e2497a609847ff9b62567c282bd262aa).
2024-01-25 00:32:40,316:INFO:discord: Command: /vouches shauuu_ Divisão 2 by shauuu_
2024-01-25 00:32:59,655:INFO:discord: Command: /vouches defender3415 Divisão 3 by shauuu_
2024-01-25 01:25:15,522:WARNING:discord.client: PyNaCl is not installed, voice will NOT be supported
2024-01-25 01:25:15,536:INFO:discord.client: logging in using static token
2024-01-25 01:25:16,649:INFO:discord.gateway: Shard ID None has connected to Gateway (Session ID: 0496197a006f498cff6fb8631fa2af35).
2024-01-25 01:25:32,542:INFO:discord: Command: /give_vouch shauuu_ teste by shauuu_
2024-01-25 01:25:52,654:INFO:discord: Command: /promote shauuu_ Divisão 2 by shauuu_
2024-01-25 01:26:22,973:INFO:discord: Command: /give_vouch shauuu_ teste2 by shauuu_
2024-01-25 01:26:51,339:INFO:discord: Command: /give_vouch shauuu_ teste casual by shauuu_
2024-01-25 01:33:41,481:WARNING:discord.client: PyNaCl is not installed, voice will NOT be supported
2024-01-25 01:33:41,507:INFO:discord.client: logging in using static token
2024-01-25 01:33:42,559:INFO:discord.gateway: Shard ID None has connected to Gateway (Session ID: 07306c5ae6acfb0f8e1c1159a196a30a).
2024-01-25 01:34:00,217:INFO:discord: Command: /vouches shauuu_ Divisão 1 by shauuu_
2024-01-25 01:34:11,001:INFO:discord: Command: /vouches shauuu_ Divisão 3 by shauuu_
2024-01-25 01:39:39,585:INFO:discord: Command: /give_vouch shauuu_ <@&1198707136427987055> by diogotv_
2024-01-25 01:39:47,765:INFO:discord: Command: /vouches shauuu_ Divisão 3 by diogotv_
2024-01-25 01:39:54,206:INFO:discord: Command: /vouches shauuu_ Divisão 3 by shauuu_
2024-01-25 01:39:56,844:INFO:discord: Command: /vouches shauuu_ Divisão 2 by shauuu_
2024-01-25 01:40:02,876:INFO:discord: Command: /vouches shauuu_ Divisão 2 by diogotv_
2024-01-25 01:40:17,511:WARNING:discord.client: PyNaCl is not installed, voice will NOT be supported
2024-01-25 01:40:17,517:INFO:discord.client: logging in using static token
2024-01-25 01:40:18,582:INFO:discord.gateway: Shard ID None has connected to Gateway (Session ID: b600447077351a01f61a6a893b1b6c3d).
2024-01-25 01:40:23,635:INFO:discord: Command: /vouches shauuu_ Divisão 2 by shauuu_
2024-01-25 01:40:34,328:INFO:discord: Command: /vouches shauuu_ Divisão 3 by shauuu_
2024-01-25 01:40:42,272:INFO:discord: Command: /vouches shauuu_ Divisão 2 by diogotv_
2024-01-25 01:40:42,471:INFO:discord: Command: /vouches shauuu_ Divisão 2 by shauuu_
2024-01-25 01:41:13,965:INFO:discord: Command: /vouches shauuu_ Divisão 3 by diogotv_
2024-01-25 01:41:18,242:INFO:discord: Command: /vouches shauuu_ Divisão 3 by shauuu_
2024-01-25 01:41:21,298:INFO:discord: Command: /vouches shauuu_ Divisão 2 by shauuu_
2024-01-25 01:41:26,585:INFO:discord: Command: /vouches shauuu_ Divisão 2 by diogotv_
2024-01-25 01:41:34,471:WARNING:discord.client: PyNaCl is not installed, voice will NOT be supported
2024-01-25 01:41:34,485:INFO:discord.client: logging in using static token
2024-01-25 01:41:35,593:INFO:discord.gateway: Shard ID None has connected to Gateway (Session ID: fcf30b6a48ea09aa4de9893b9f7f6299).
2024-01-25 01:41:42,367:INFO:discord: Command: /vouches shauuu_ Divisão 2 by shauuu_
2024-01-25 01:41:42,908:INFO:discord: Command: /vouches shauuu_ Divisão 2 by diogotv_
2024-01-25 01:41:49,997:INFO:discord: Command: /vouches shauuu_ Divisão 3 by diogotv_
2024-01-25 01:41:52,683:INFO:discord: Command: /vouches shauuu_ Divisão 3 by shauuu_
2024-01-25 01:42:03,033:INFO:discord: Command: /give_vouch shauuu_ <@&1198707105780207736> by diogotv_
2024-01-25 01:42:11,507:INFO:discord: Command: /vouches shauuu_ Divisão 2 by diogotv_
2024-01-25 01:42:12,558:INFO:discord: Command: /vouches shauuu_ Divisão 2 by shauuu_
2024-01-25 01:42:26,762:INFO:discord: Command: /vouches shauuu_ Divisão 3 by diogotv_
2024-01-25 01:43:29,338:INFO:discord: Command: /vouches shauuu_ Divisão 1 by diogotv_
2024-01-25 01:43:29,863:INFO:discord: Command: /vouches shauuu_ Divisão 1 by shauuu_
2024-01-25 01:43:48,013:WARNING:discord.client: PyNaCl is not installed, voice will NOT be supported
2024-01-25 01:43:48,031:INFO:discord.client: logging in using static token
2024-01-25 01:43:49,124:INFO:discord.gateway: Shard ID None has connected to Gateway (Session ID: fbd3877de161d403503459fb161ecb32).
2024-01-25 01:43:54,954:INFO:discord: Command: /vouches shauuu_ Divisão 2 by shauuu_
2024-01-25 01:44:11,165:WARNING:discord.client: PyNaCl is not installed, voice will NOT be supported
2024-01-25 01:44:11,179:INFO:discord.client: logging in using static token
2024-01-25 01:44:12,266:INFO:discord.gateway: Shard ID None has connected to Gateway (Session ID: e59f88c2f01121fa37a24574b6e37992).
2024-01-25 01:44:16,037:INFO:discord: Command: /promote shauuu_ Divisão 2 by diogotv_
2024-01-25 01:44:16,541:INFO:discord: Command: /vouches shauuu_ Divisão 2 by shauuu_
2024-01-25 01:44:19,381:ERROR:discord.app_commands.tree: Ignoring exception in command 'promote'
Traceback (most recent call last):
  File "D:\PyCharmProjects\Vouch Bot\.venv\lib\site-packages\discord\app_commands\commands.py", line 827, in _do_call
    return await self._callback(self.binding, interaction, **params)  # type: ignore
  File "D:\PyCharmProjects\Vouch Bot\commands.py", line 188, in promote
    await ctx.response.send_message(embed=embed, ephemeral=True)
  File "D:\PyCharmProjects\Vouch Bot\.venv\lib\site-packages\discord\interactions.py", line 801, in send_message
    await adapter.create_interaction_response(
  File "D:\PyCharmProjects\Vouch Bot\.venv\lib\site-packages\discord\webhook\async_.py", line 219, in request
    raise NotFound(response, data)
discord.errors.NotFound: 404 Not Found (error code: 10062): Unknown interaction

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\PyCharmProjects\Vouch Bot\.venv\lib\site-packages\discord\app_commands\tree.py", line 1248, in _call
    await command._invoke_with_namespace(interaction, namespace)
  File "D:\PyCharmProjects\Vouch Bot\.venv\lib\site-packages\discord\app_commands\commands.py", line 853, in _invoke_with_namespace
    return await self._do_call(interaction, transformed_values)
  File "D:\PyCharmProjects\Vouch Bot\.venv\lib\site-packages\discord\app_commands\commands.py", line 846, in _do_call
    raise CommandInvokeError(self, e) from e
discord.app_commands.errors.CommandInvokeError: Command 'promote' raised an exception: NotFound: 404 Not Found (error code: 10062): Unknown interaction
2024-01-25 01:44:34,411:INFO:discord: Command: /give_vouch shauuu_ <@&1198707078487883786> by diogotv_
2024-01-25 01:44:42,901:INFO:discord: Command: /vouches shauuu_ Divisão 1 by diogotv_
2024-01-25 01:44:49,495:INFO:discord: Command: /vouches shauuu_ Divisão 1 by shauuu_
2024-01-25 01:44:51,694:INFO:discord: Command: /vouches shauuu_ Divisão 2 by diogotv_
2024-01-25 01:51:55,710:WARNING:discord.client: PyNaCl is not installed, voice will NOT be supported
2024-01-25 01:51:55,716:INFO:discord.client: logging in using static token
2024-01-25 01:51:57,099:INFO:discord.gateway: Shard ID None has connected to Gateway (Session ID: 3227ec172c103a5819277409385101f6).
2024-01-25 02:02:10,431:WARNING:discord.client: PyNaCl is not installed, voice will NOT be supported
2024-01-25 02:02:10,444:INFO:discord.client: logging in using static token
2024-01-25 02:02:11,488:INFO:discord.gateway: Shard ID None has connected to Gateway (Session ID: 0653a39e169a819efdf031cd30c9083f).
2024-01-25 02:02:25,477:INFO:discord: Command: /disponivel Choice(name='1v1', value=1) by shauuu_
2024-01-25 02:03:22,663:INFO:discord: Command: /disponivel Choice(name='2v2', value=2) by shauuu_
2024-01-25 02:03:30,192:INFO:discord: Command: /disponivel Choice(name='2v2', value=2) by shauuu_
2024-01-25 02:03:50,541:WARNING:discord.client: PyNaCl is not installed, voice will NOT be supported
2024-01-25 02:03:50,559:INFO:discord.client: logging in using static token
2024-01-25 02:03:51,678:INFO:discord.gateway: Shard ID None has connected to Gateway (Session ID: 686e9314c679216c21d104fea93a1c21).
2024-01-25 02:04:08,890:INFO:discord: Command: /disponivel Choice(name='1v1', value=1) by shauuu_
2024-01-25 02:04:20,208:INFO:discord: Command: /disponivel Choice(name='3v3', value=3) by shauuu_
2024-01-25 02:04:34,996:INFO:discord: Command: /disponivel Choice(name='4v4', value=4) by shauuu_
2024-01-25 02:14:44,841:INFO:discord: Command: /promote shauuu_ Divisão 2 by shauuu_
2024-01-25 02:14:45,290:ERROR:discord.app_commands.tree: Ignoring exception in command 'promote'
Traceback (most recent call last):
  File "D:\PyCharmProjects\Vouch Bot\.venv\lib\site-packages\discord\app_commands\commands.py", line 827, in _do_call
    return await self._callback(self.binding, interaction, **params)  # type: ignore
  File "D:\PyCharmProjects\Vouch Bot\commands.py", line 181, in promote
    await member.remove_roles(member_role)
  File "D:\PyCharmProjects\Vouch Bot\.venv\lib\site-packages\discord\member.py", line 1096, in remove_roles
    await req(guild_id, user_id, role.id, reason=reason)
  File "D:\PyCharmProjects\Vouch Bot\.venv\lib\site-packages\discord\http.py", line 739, in request
    raise Forbidden(response, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50013): Missing Permissions

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\PyCharmProjects\Vouch Bot\.venv\lib\site-packages\discord\app_commands\tree.py", line 1248, in _call
    await command._invoke_with_namespace(interaction, namespace)
  File "D:\PyCharmProjects\Vouch Bot\.venv\lib\site-packages\discord\app_commands\commands.py", line 853, in _invoke_with_namespace
    return await self._do_call(interaction, transformed_values)
  File "D:\PyCharmProjects\Vouch Bot\.venv\lib\site-packages\discord\app_commands\commands.py", line 846, in _do_call
    raise CommandInvokeError(self, e) from e
discord.app_commands.errors.CommandInvokeError: Command 'promote' raised an exception: Forbidden: 403 Forbidden (error code: 50013): Missing Permissions
2024-01-25 02:15:23,551:WARNING:discord.client: PyNaCl is not installed, voice will NOT be supported
2024-01-25 02:15:23,564:INFO:discord.client: logging in using static token
2024-01-25 02:15:24,754:INFO:discord.gateway: Shard ID None has connected to Gateway (Session ID: 9499366351d39a1c5f0ef37bbb214478).
2024-01-25 02:15:29,327:INFO:discord: Command: /promote shauuu_ Divisão 2 by shauuu_
2024-01-25 02:15:29,841:ERROR:discord.app_commands.tree: Ignoring exception in command 'promote'
Traceback (most recent call last):
  File "D:\PyCharmProjects\Vouch Bot\.venv\lib\site-packages\discord\app_commands\commands.py", line 827, in _do_call
    return await self._callback(self.binding, interaction, **params)  # type: ignore
  File "D:\PyCharmProjects\Vouch Bot\commands.py", line 181, in promote
    await member.remove_roles(member_role)
  File "D:\PyCharmProjects\Vouch Bot\.venv\lib\site-packages\discord\member.py", line 1096, in remove_roles
    await req(guild_id, user_id, role.id, reason=reason)
  File "D:\PyCharmProjects\Vouch Bot\.venv\lib\site-packages\discord\http.py", line 739, in request
    raise Forbidden(response, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50013): Missing Permissions

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\PyCharmProjects\Vouch Bot\.venv\lib\site-packages\discord\app_commands\tree.py", line 1248, in _call
    await command._invoke_with_namespace(interaction, namespace)
  File "D:\PyCharmProjects\Vouch Bot\.venv\lib\site-packages\discord\app_commands\commands.py", line 853, in _invoke_with_namespace
    return await self._do_call(interaction, transformed_values)
  File "D:\PyCharmProjects\Vouch Bot\.venv\lib\site-packages\discord\app_commands\commands.py", line 846, in _do_call
    raise CommandInvokeError(self, e) from e
discord.app_commands.errors.CommandInvokeError: Command 'promote' raised an exception: Forbidden: 403 Forbidden (error code: 50013): Missing Permissions
2024-01-25 02:16:48,478:WARNING:discord.client: PyNaCl is not installed, voice will NOT be supported
2024-01-25 02:16:48,527:INFO:discord.client: logging in using static token
2024-01-25 02:16:49,751:INFO:discord.gateway: Shard ID None has connected to Gateway (Session ID: eb70126ed90c8566928e39764a57e40a).
2024-01-25 02:16:53,693:INFO:discord: Command: /promote shauuu_ Divisão 2 by shauuu_
2024-01-25 02:16:54,160:ERROR:discord.app_commands.tree: Ignoring exception in command 'promote'
Traceback (most recent call last):
  File "D:\PyCharmProjects\Vouch Bot\.venv\lib\site-packages\discord\app_commands\commands.py", line 827, in _do_call
    return await self._callback(self.binding, interaction, **params)  # type: ignore
  File "D:\PyCharmProjects\Vouch Bot\commands.py", line 181, in promote
    await member.remove_roles(member_role)
  File "D:\PyCharmProjects\Vouch Bot\.venv\lib\site-packages\discord\member.py", line 1096, in remove_roles
    await req(guild_id, user_id, role.id, reason=reason)
  File "D:\PyCharmProjects\Vouch Bot\.venv\lib\site-packages\discord\http.py", line 739, in request
    raise Forbidden(response, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50013): Missing Permissions

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\PyCharmProjects\Vouch Bot\.venv\lib\site-packages\discord\app_commands\tree.py", line 1248, in _call
    await command._invoke_with_namespace(interaction, namespace)
  File "D:\PyCharmProjects\Vouch Bot\.venv\lib\site-packages\discord\app_commands\commands.py", line 853, in _invoke_with_namespace
    return await self._do_call(interaction, transformed_values)
  File "D:\PyCharmProjects\Vouch Bot\.venv\lib\site-packages\discord\app_commands\commands.py", line 846, in _do_call
    raise CommandInvokeError(self, e) from e
discord.app_commands.errors.CommandInvokeError: Command 'promote' raised an exception: Forbidden: 403 Forbidden (error code: 50013): Missing Permissions
2024-01-25 02:18:15,862:WARNING:discord.client: PyNaCl is not installed, voice will NOT be supported
2024-01-25 02:18:15,877:INFO:discord.client: logging in using static token
2024-01-25 02:18:16,926:INFO:discord.gateway: Shard ID None has connected to Gateway (Session ID: e8eb55c7757c8ef905397821c78c8c49).
2024-01-25 02:18:21,480:INFO:discord: Command: /promote shauuu_ Divisão 2 by shauuu_
2024-01-25 02:18:51,222:INFO:discord: Command: /promote shauuu_ Divisão 2 by shauuu_
2024-01-25 02:19:16,891:INFO:discord: Command: /disponivel Choice(name='2v2', value=2) by shauuu_
2024-01-25 02:24:35,168:WARNING:discord.client: PyNaCl is not installed, voice will NOT be supported
2024-01-25 02:24:35,182:INFO:discord.client: logging in using static token
2024-01-25 02:24:36,301:INFO:discord.gateway: Shard ID None has connected to Gateway (Session ID: b977effa934a7700be793a317b30e511).
2024-01-25 02:24:48,902:INFO:discord: Command: /disponivel Choice(name='1v1', value=1) by shauuu_
2024-01-25 02:25:23,468:INFO:discord: Command: /disponivel Choice(name='1v1', value=1) by diogotv_
2024-01-25 02:26:02,883:INFO:discord: Command: /disponivel Choice(name='1v1', value=1) by diogotv_
2024-01-25 02:26:08,660:INFO:discord: Command: /disponivel Choice(name='1v1', value=1) by shauuu_
2024-01-25 02:26:25,187:INFO:discord: Command: /vouches diogotv_ Divisão 3 by diogotv_
2024-01-25 02:26:40,539:INFO:discord: Command: /vouches shauuu_ Divisão 1 by shauuu_
2024-01-25 02:27:48,631:WARNING:discord.client: PyNaCl is not installed, voice will NOT be supported
2024-01-25 02:27:48,647:INFO:discord.client: logging in using static token
2024-01-25 02:27:49,761:INFO:discord.gateway: Shard ID None has connected to Gateway (Session ID: 79cc81dd504f741deec4f02f937434fd).
2024-01-25 02:28:02,205:INFO:discord: Command: /disponivel Choice(name='1v1', value=1) by shauuu_
2024-01-25 02:28:51,490:WARNING:discord.client: PyNaCl is not installed, voice will NOT be supported
2024-01-25 02:28:51,496:INFO:discord.client: logging in using static token
2024-01-25 02:28:52,502:INFO:discord.gateway: Shard ID None has connected to Gateway (Session ID: 3705c34c58c3309931f0a5588e45af3d).
2024-01-25 02:29:07,881:INFO:discord: Command: /disponivel Choice(name='1v1', value=1) by shauuu_
2024-01-25 02:29:16,428:WARNING:discord.client: PyNaCl is not installed, voice will NOT be supported
2024-01-25 02:29:16,434:INFO:discord.client: logging in using static token
2024-01-25 02:29:17,459:INFO:discord.gateway: Shard ID None has connected to Gateway (Session ID: dfe6972695bf6097ab6945a9ef63b37a).
2024-01-25 02:29:21,799:INFO:discord: Command: /disponivel Choice(name='1v1', value=1) by shauuu_
2024-01-25 02:29:30,108:INFO:discord: Command: /disponivel Choice(name='1v1', value=1) by diogotv_
2024-01-25 02:29:54,036:INFO:discord: Command: /disponivel Choice(name='1v1', value=1) by diogotv_
2024-01-25 13:29:06,849:WARNING:discord.client: PyNaCl is not installed, voice will NOT be supported
2024-01-25 13:29:06,966:INFO:discord.client: logging in using static token
2024-01-25 13:29:08,182:INFO:discord.gateway: Shard ID None has connected to Gateway (Session ID: 22dec1baca5e9c0d470be8732b385549).
2024-01-25 13:29:28,662:INFO:discord: Command: /disponivel Choice(name='1v1', value=1) by shauuu_
2024-01-25 13:34:05,539:WARNING:discord.client: PyNaCl is not installed, voice will NOT be supported
2024-01-25 13:34:05,558:INFO:discord.client: logging in using static token
2024-01-25 13:34:06,673:INFO:discord.gateway: Shard ID None has connected to Gateway (Session ID: e253b52f88e136f930e9253119b41b5e).
2024-01-25 13:41:39,167:WARNING:discord.client: PyNaCl is not installed, voice will NOT be supported
2024-01-25 13:41:39,185:INFO:discord.client: logging in using static token
2024-01-25 13:41:40,335:INFO:discord.gateway: Shard ID None has connected to Gateway (Session ID: 6b598f40b3557fbd41467fe0c6414686).
2024-01-25 13:42:11,087:WARNING:discord.client: PyNaCl is not installed, voice will NOT be supported
2024-01-25 13:42:11,101:INFO:discord.client: logging in using static token
2024-01-25 13:42:12,255:INFO:discord.gateway: Shard ID None has connected to Gateway (Session ID: 9ebacfbbd71cc980a02e1f3035986207).
2024-01-25 13:42:21,684:WARNING:discord.client: PyNaCl is not installed, voice will NOT be supported
2024-01-25 13:42:21,697:INFO:discord.client: logging in using static token
2024-01-25 13:42:22,749:INFO:discord.gateway: Shard ID None has connected to Gateway (Session ID: 82d1530f881315b5ea716b7321e36a7f).
2024-01-25 13:42:37,335:INFO:discord: Command: /purge diogotv_ by shauuu_
2024-01-25 13:42:52,567:INFO:discord: Command: /purge diogotv_ by shauuu_
